import { COLOR_THEMES, DEFAULT_CONTOUR_MAJOR_WIDTH, type ColorTheme, type CompositionId, type StyleConfig, type ThemeDefinition } from '~/types'

export const COMPOSITION_IDS = [
  'editorial-tall',
  'park-quad',
  'travel-banner',
  'riso-stack',
  'blueprint-grid',
  'blueprint-strava',
  'journal-spread',
  'modernist-block',
  'splits-grid',
  'bib-numerals',
  'darksky-stars',
  'botanical-plate',
  'brutalist-slab',
] as const satisfies readonly CompositionId[]

type RefinedThemeDefinition = ThemeDefinition & {
  composition: CompositionId
  audience: string
  family: string
  map_defaults: Partial<StyleConfig>
}

const REFINED_CONTOUR_OPACITY = 0.34
const REFINED_CONTOUR_MINOR_WIDTH = 0.72

function mapDefaults(defaults: Partial<StyleConfig>): Partial<StyleConfig> {
  const atlasStyleId = typeof defaults.preset === 'string' && defaults.preset.startsWith('radmaps-')
    ? { atlas_style_id: defaults.preset }
    : {}
  const contourDefaults = defaults.show_contours
    ? {
        contour_opacity: REFINED_CONTOUR_OPACITY,
        contour_minor_width: REFINED_CONTOUR_MINOR_WIDTH,
        contour_major_width: DEFAULT_CONTOUR_MAJOR_WIDTH,
      }
    : {}

  return {
    ...contourDefaults,
    ...defaults,
    ...atlasStyleId,
  }
}

export const REFINED_THEMES = [
  {
    id: 'editorial-minimal',
    label: 'Editorial',
    family: 'Minimal',
    audience: 'Gallery / collector',
    dark: false,
    background_color: '#F6F2EA',
    label_bg_color: '#F6F2EA',
    label_text_color: '#171513',
    route_color: '#B5251D',
    water_color: '#D6DCE0',
    land_color: '#EFE9DD',
    base_tile_style: 'carto-light',
    contour_color: '#CFC6B6',
    contour_major_color: '#A89C86',
    font_family: 'Playfair Display',
    body_font_family: 'Libre Baskerville',
    border_style: 'none',
    tile_grain: 0,
    composition: 'editorial-tall',
    map_defaults: mapDefaults({ preset: 'radmaps-simple-contour', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'usgs-vintage',
    label: 'USGS',
    family: 'Topographic',
    audience: 'National Park / tourist',
    dark: false,
    background_color: '#EDE3CC',
    label_bg_color: '#EDE3CC',
    label_text_color: '#3A2A14',
    route_color: '#B43A1F',
    water_color: '#9CB7C0',
    land_color: '#E8DCBE',
    base_tile_style: 'maptiler-topo',
    contour_color: '#9C7A48',
    contour_major_color: '#6B4D26',
    font_family: 'DM Serif Display',
    body_font_family: 'Libre Baskerville',
    border_style: 'thin',
    tile_grain: 0.32,
    composition: 'park-quad',
    map_defaults: mapDefaults({ preset: 'radmaps-topographic', show_roads: false, show_place_labels: true, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'midcentury-travel',
    label: 'Mid-Century',
    family: 'Travel poster',
    audience: 'National Park / tourist',
    dark: false,
    background_color: '#E8DAB8',
    label_bg_color: '#1F3325',
    label_text_color: '#F0E5C5',
    route_color: '#D4603A',
    water_color: '#7FA098',
    land_color: '#D8C594',
    base_tile_style: 'carto-light',
    contour_color: '#B89060',
    contour_major_color: '#7A5830',
    font_family: 'Oswald',
    body_font_family: 'Work Sans',
    border_style: 'none',
    tile_grain: 0.12,
    composition: 'travel-banner',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      tile_effect: 'none',
      show_grid: false,
      place_labels_color: '#3A4A2A',
      poi_labels_color: '#3A4A2A',
      atlas_layer_settings: {
        place: { label_color: '#3A4A2A', halo_color: '#E8DAB8' },
        poi: { label_color: '#3A4A2A' },
      },
    }),
  },
  {
    id: 'risograph',
    label: 'Risograph',
    family: 'Print',
    audience: 'Trail marketing / merch',
    dark: false,
    background_color: '#F2EAD2',
    label_bg_color: '#F2EAD2',
    label_text_color: '#1A1F45',
    route_color: '#E84A2A',
    water_color: '#3F6FB8',
    land_color: '#E8DDB8',
    base_tile_style: 'carto-light',
    contour_color: '#3F6FB8',
    contour_major_color: '#1A1F45',
    font_family: 'Oswald',
    body_font_family: 'Space Grotesk',
    border_style: 'none',
    tile_grain: 0.40,
    composition: 'riso-stack',
    map_defaults: mapDefaults({ preset: 'radmaps-minimalist', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'duotone', show_grid: false }),
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    family: 'Technical',
    audience: 'Engineer / surveyor',
    dark: true,
    background_color: '#0F2D52',
    label_bg_color: '#0F2D52',
    label_text_color: '#D0E4FF',
    route_color: '#FFD046',
    water_color: '#091F3A',
    land_color: '#143664',
    base_tile_style: 'carto-dark',
    contour_color: '#3D7AC2',
    contour_major_color: '#7CB0E8',
    font_family: 'Space Grotesk',
    body_font_family: 'Space Grotesk',
    border_style: 'thin',
    tile_grain: 0.04,
    composition: 'blueprint-grid',
    show_grid: true,
    map_defaults: mapDefaults({ preset: 'radmaps-alidade-dark', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: true, grid_scope: 'map', grid_opacity: 0.16, grid_weight: 1 }),
  },
  {
    id: 'blueprint-strava',
    label: 'Blueprint · Strava',
    family: 'Technical',
    audience: 'Strava ride / data import',
    dark: true,
    background_color: '#0F2D52',
    label_bg_color: '#0F2D52',
    label_text_color: '#D0E4FF',
    route_color: '#FC4C02',
    water_color: '#091F3A',
    land_color: '#143664',
    base_tile_style: 'carto-dark',
    contour_color: '#3D7AC2',
    contour_major_color: '#7CB0E8',
    font_family: 'Space Grotesk',
    body_font_family: 'Space Grotesk',
    border_style: 'thin',
    tile_grain: 0.04,
    composition: 'blueprint-strava',
    show_grid: true,
    map_defaults: mapDefaults({ preset: 'radmaps-alidade-dark', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: true, grid_scope: 'map', grid_opacity: 0.16, grid_weight: 1 }),
  },
  {
    id: 'field-journal',
    label: 'Journal',
    family: 'Illustrated',
    audience: 'Hiker / traveler',
    dark: false,
    background_color: '#F1E9D8',
    label_bg_color: '#F1E9D8',
    label_text_color: '#3A2A1A',
    route_color: '#A23B26',
    water_color: '#A8B8B0',
    land_color: '#EBE0C8',
    base_tile_style: 'maptiler-outdoor',
    contour_color: '#9C8868',
    contour_major_color: '#6E5C3E',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Libre Baskerville',
    border_style: 'thin',
    tile_grain: 0.22,
    composition: 'journal-spread',
    map_defaults: mapDefaults({ preset: 'radmaps-natural', show_roads: false, show_place_labels: true, show_hillshade: true, show_contours: true, contour_detail: 5, tile_effect: 'layer-color', show_grid: false }),
  },
  {
    id: 'bold-modern',
    label: 'Modernist',
    family: 'Graphic',
    audience: 'Designer / collector',
    dark: false,
    background_color: '#F1EAE0',
    label_bg_color: '#1C1917',
    label_text_color: '#F1EAE0',
    route_color: '#FF3A2E',
    water_color: '#1C1917',
    land_color: '#F1EAE0',
    base_tile_style: 'carto-light',
    contour_color: '#A8A29E',
    contour_major_color: '#1C1917',
    font_family: 'Big Shoulders Display',
    body_font_family: 'DM Sans',
    border_style: 'thick',
    tile_grain: 0,
    composition: 'modernist-block',
    map_defaults: mapDefaults({
      preset: 'radmaps-toner-light',
      show_roads: false,
      show_place_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 6,
      contour_opacity: 0.38,
      contour_minor_width: 0.85,
      contour_major_width: DEFAULT_CONTOUR_MAJOR_WIDTH,
      show_grid: false,
    }),
  },
  {
    id: 'contour-wash',
    label: 'Contour Wash',
    family: 'Contour study',
    audience: 'Topo art / route keepsake',
    dark: false,
    background_color: '#EDE4D7',
    label_bg_color: '#EDE4D7',
    label_text_color: '#2A180B',
    route_color: '#9A5E57',
    water_color: '#B7D8EF',
    land_color: '#D7E8F7',
    base_tile_style: 'carto-light',
    contour_color: '#75A8D2',
    contour_major_color: '#4C7FA9',
    font_family: 'Big Shoulders Display',
    body_font_family: 'DM Sans',
    border_style: 'thick',
    tile_grain: 0.08,
    composition: 'modernist-block',
    map_defaults: mapDefaults({
      preset: 'radmaps-contour-wash',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      contour_opacity: 0.46,
      contour_minor_width: 0.7,
      contour_major_width: DEFAULT_CONTOUR_MAJOR_WIDTH,
      tile_effect: 'none',
      show_grid: false,
      atlas_layer_settings: {
        landcover: { color: '#D7E8F7', opacity: 0.94 },
        park: { fill_color: '#CFE0EA', opacity: 0.26 },
        water: { fill_color: '#B7D8EF', fill_opacity: 0.34 },
        waterway: { color: '#75A8D2', opacity: 0.42, width: 0.9 },
        transportation: { opacity: 0.16, major_color: '#8AA6BD', minor_color: '#B5C8D6', trail_color: '#7D9AB3', show_major: false, show_minor: false, show_trails: false },
        contour: { minor_color: '#75A8D2', major_color: '#4C7FA9', minor_opacity: 0.46, major_width: 0.55 },
        place: { label_color: '#4F6D83', label_opacity: 0.20, font_size: 12, halo_color: '#D7E8F7' },
        poi: { label_opacity: 0.10 },
      },
    }),
  },
  {
    id: 'splits-stats',
    label: 'Splits',
    family: 'Data-forward',
    audience: 'Runner / cyclist',
    dark: true,
    background_color: '#0E0E10',
    label_bg_color: '#0E0E10',
    label_text_color: '#F4F2EE',
    route_color: '#FC4C02',
    water_color: '#101820',
    land_color: '#161618',
    base_tile_style: 'carto-dark',
    contour_color: '#2A2A2E',
    contour_major_color: '#56565E',
    font_family: 'Space Grotesk',
    body_font_family: 'Space Grotesk',
    border_style: 'none',
    tile_grain: 0.08,
    composition: 'splits-grid',
    map_defaults: mapDefaults({ preset: 'radmaps-alidade-dark', show_roads: true, show_place_labels: false, show_hillshade: false, show_contours: false, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'marathon-bib',
    label: 'Marathon',
    family: 'Commemorative',
    audience: 'Marathon / event',
    dark: false,
    background_color: '#FAFAF7',
    label_bg_color: '#FAFAF7',
    label_text_color: '#0A0A0A',
    route_color: '#1A4D8F',
    water_color: '#D8E2EC',
    land_color: '#F0EDE7',
    base_tile_style: 'carto-light',
    contour_color: '#D6CFC2',
    contour_major_color: '#A39A88',
    font_family: 'Bebas Neue',
    body_font_family: 'DM Sans',
    border_style: 'thick',
    tile_grain: 0,
    composition: 'bib-numerals',
    map_defaults: mapDefaults({ preset: 'radmaps-alidade', show_roads: true, show_place_labels: false, show_hillshade: false, show_contours: false, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'dark-sky',
    label: 'Dark Sky',
    family: 'Atmospheric',
    audience: 'Backcountry / dark sky park',
    dark: true,
    background_color: '#050814',
    label_bg_color: '#050814',
    label_text_color: '#E8DEC0',
    route_color: '#F4B942',
    water_color: '#040712',
    land_color: '#070A14',
    base_tile_style: 'carto-dark',
    contour_color: '#24335F',
    contour_major_color: '#4A6299',
    font_family: 'Fjalla One',
    body_font_family: 'Work Sans',
    border_style: 'none',
    tile_grain: 0.22,
    composition: 'darksky-stars',
    map_defaults: mapDefaults({
      preset: 'radmaps-night-relief',
      show_roads: false,
      show_place_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      tile_effect: 'layer-color',
      show_grid: false,
      trail_label_style: 'leader-lines',
      leader_label_auto_fit: true,
      leader_label_scale: 0.9,
      leader_label_font_family: 'Fjalla One',
      segment_casing_color: '#050814',
      segment_casing_width: 2,
      atlas_layer_settings: {
        landcover: { color: '#070A14', opacity: 0.94 },
        park: { fill_color: '#0B1020', opacity: 0.18 },
        water: {
          fill_color: '#040712',
          fill_opacity: 0.88,
          waterway_color: '#18294C',
          waterway_opacity: 0.48,
          waterway_width: 0.85,
        },
        waterway: { color: '#18294C', opacity: 0.50, width: 0.85 },
        transportation: {
          major_color: '#28324C',
          minor_color: '#202942',
          road_color: '#202942',
          trail_color: '#F4B942',
          opacity: 0.38,
          show_major: false,
          show_minor: false,
          show_trails: true,
          trail_width: 0.9,
        },
        contour: {
          minor_color: '#24335F',
          major_color: '#4A6299',
          minor_opacity: 0.30,
          major_opacity: 0.42,
          minor_width: REFINED_CONTOUR_MINOR_WIDTH,
          major_width: DEFAULT_CONTOUR_MAJOR_WIDTH,
        },
        building: { fill_color: '#111827', opacity: 0.08 },
        place: {
          label_color: '#D8CFB8',
          label_opacity: 0.24,
          halo_color: '#050814',
          font_size: 10,
        },
        poi: { label_color: '#D8CFB8', label_opacity: 0.16 },
      },
    }),
  },
  {
    id: 'botanical',
    label: 'Botanical',
    family: 'Naturalist',
    audience: 'Garden / landscape',
    dark: false,
    background_color: '#EDE6D6',
    label_bg_color: '#EDE6D6',
    label_text_color: '#2A3A28',
    route_color: '#7B3A2A',
    water_color: '#A6BFA6',
    land_color: '#E2DCC4',
    base_tile_style: 'maptiler-outdoor',
    contour_color: '#9CA77A',
    contour_major_color: '#5E6E3E',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Libre Baskerville',
    border_style: 'thin',
    tile_grain: 0.10,
    composition: 'botanical-plate',
    map_defaults: mapDefaults({ preset: 'radmaps-natural', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'brutalist',
    label: 'Brutalist',
    family: 'Concrete',
    audience: 'Urban runner / cyclist',
    dark: false,
    background_color: '#E5E1D8',
    label_bg_color: '#E5E1D8',
    label_text_color: '#0A0A0A',
    route_color: '#FF1F1F',
    water_color: '#B8B8B0',
    land_color: '#D8D4CB',
    base_tile_style: 'carto-light',
    contour_color: '#9A968E',
    contour_major_color: '#4C4844',
    font_family: 'Bebas Neue',
    body_font_family: 'Space Grotesk',
    border_style: 'thick',
    tile_grain: 0.06,
    composition: 'brutalist-slab',
    map_defaults: mapDefaults({ preset: 'radmaps-toner-light', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
] as const satisfies readonly RefinedThemeDefinition[]

export const REFINED_THEME_IDS = REFINED_THEMES.map(theme => theme.id) as ColorTheme[]
export const ALL_COLOR_THEME_IDS = Array.from(new Set([...COLOR_THEMES.map(theme => theme.id), ...REFINED_THEME_IDS])) as ColorTheme[]

export const LEGACY_THEME_MIGRATION_TARGETS = Object.fromEntries(
  COLOR_THEMES
    .filter(theme => theme.legacy && theme.migration_target)
    .map(theme => [theme.id, theme.migration_target]),
) as Partial<Record<ColorTheme, ColorTheme>>

export function getRefinedThemeById(id: ColorTheme | string): RefinedThemeDefinition | undefined {
  return REFINED_THEMES.find(theme => theme.id === id)
}

export function getThemeDefinition(id: ColorTheme | string): ThemeDefinition | undefined {
  return getRefinedThemeById(id) ?? COLOR_THEMES.find(theme => theme.id === id)
}
