import { COLOR_THEMES, DEFAULT_CONTOUR_MAJOR_WIDTH, type ColorTheme, type CompositionId, type StyleConfig, type ThemeDefinition, type ThemeEditableField } from '~/types'

export const COMPOSITION_IDS = [
  'editorial-tall',
  'park-quad',
  'travel-banner',
  'riso-stack',
  'blueprint-grid',
  'blueprint-strava',
  'journal-spread',
  'modernist-block',
  'splits-grid',
  'bib-numerals',
  'darksky-stars',
  'botanical-plate',
  'brutalist-slab',
  'art-wash',
  'place-frame',
  'sea-chart',
  'transit-diagram',
] as const satisfies readonly CompositionId[]

type RefinedThemeDefinition = ThemeDefinition & {
  composition: CompositionId
  audience: string
  family: string
  map_defaults: Partial<StyleConfig>
  review_decision?: 'keep' | 'revise' | 'merge' | 'new'
  colorway_of?: ColorTheme
  editable_fields: ThemeEditableField[]
}

type RefinedThemeRecipe = Omit<RefinedThemeDefinition, 'editable_fields'> & {
  editable_fields?: ThemeEditableField[]
}

const DEFAULT_REFINED_EDITABLE_FIELDS = [
  'trail_name',
  'location_text',
  'occasion_text',
  'route_color',
  'colorway',
  'map_camera',
  'print_size',
] as const satisfies readonly ThemeEditableField[]

function withEditableDefaults(theme: RefinedThemeRecipe): RefinedThemeDefinition {
  return {
    ...theme,
    editable_fields: Array.from(new Set(theme.editable_fields ?? DEFAULT_REFINED_EDITABLE_FIELDS)),
  }
}

const REFINED_CONTOUR_OPACITY = 0.30
const REFINED_CONTOUR_MINOR_WIDTH = 0.64

function mapDefaults(defaults: Partial<StyleConfig>): Partial<StyleConfig> {
  const atlasStyleId = typeof defaults.preset === 'string' && defaults.preset.startsWith('radmaps-')
    ? { atlas_style_id: defaults.preset }
    : {}
  const contourDefaults = defaults.show_contours
    ? {
        contour_opacity: REFINED_CONTOUR_OPACITY,
        contour_minor_width: REFINED_CONTOUR_MINOR_WIDTH,
        contour_major_width: DEFAULT_CONTOUR_MAJOR_WIDTH,
      }
    : {}

  return {
    show_elevation_profile: false,
    trail_label_style: undefined,
    ...contourDefaults,
    ...defaults,
    ...atlasStyleId,
  }
}

const REFINED_THEME_RECIPES = [
  {
    id: 'editorial-minimal',
    label: 'Editorial',
    family: 'Minimal',
    audience: 'Gallery / collector',
    review_decision: 'keep',
    dark: false,
    background_color: '#F8F3EA',
    label_bg_color: '#F8F3EA',
    label_text_color: '#171410',
    route_color: '#9A3B27',
    water_color: '#D8DEE0',
    land_color: '#F1EADD',
    base_tile_style: 'carto-light',
    contour_color: '#C9CDD0',
    contour_major_color: '#8D9294',
    font_family: 'Playfair Display',
    body_font_family: 'Source Serif 4',
    border_style: 'none',
    tile_grain: 0,
    composition: 'editorial-tall',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      contour_opacity: 0.30,
      contour_minor_width: 0.50,
      contour_major_width: 0.56,
      route_width: 3.4,
      pin_color: '#9A3B27',
      pin_opacity: 0.96,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      atlas_layer_settings: {
        landcover: { color: '#F1EADD', opacity: 0.98, texture: 'paper' },
        water: { fill_color: '#D8DEE0', fill_opacity: 0.18, waterway_color: '#B7C8CC', waterway_opacity: 0.20 },
        waterway: { color: '#B7C8CC', opacity: 0.20, width: 0.58 },
        contour: { minor_color: '#C9CDD0', major_color: '#8D9294', minor_opacity: 0.24, major_opacity: 0.34, minor_width: 0.50, major_width: 0.56 },
      },
    }),
  },
  {
    id: 'usgs-vintage',
    label: 'USGS Heritage',
    family: 'Topographic',
    audience: 'National Park / tourist',
    review_decision: 'keep',
    dark: false,
    background_color: '#F0ECDE',
    label_bg_color: '#F0ECDE',
    label_text_color: '#243021',
    route_color: '#9D3825',
    water_color: '#DCD4BE',
    land_color: '#F0ECDE',
    base_tile_style: 'carto-light',
    contour_color: '#C5AA72',
    contour_major_color: '#617349',
    font_family: 'Libre Baskerville',
    body_font_family: 'Source Sans 3',
    border_style: 'thin',
    tile_grain: 0.46,
    composition: 'park-quad',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      contour_minor_width: 0.72,
      contour_major_width: 0.92,
      route_width: 3.15,
      route_opacity: 0.96,
      pin_color: '#9D3825',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: true,
        park: true,
        water: false,
        waterway: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#F0ECDE', opacity: 0.98, texture: 'paper' },
        park: { fill_color: '#F0ECDE', opacity: 0, boundary_color: '#617349', boundary_opacity: 0.78 },
        water: { fill_color: '#F0ECDE', fill_opacity: 0, waterway_color: '#C5AA72', waterway_opacity: 0 },
        waterway: { color: '#C5AA72', opacity: 0, width: 0.8 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        building: { fill_color: '#F0ECDE', opacity: 0 },
        contour: { minor_color: '#C5AA72', major_color: '#617349', minor_opacity: 0.62, major_opacity: 0.70, minor_width: 0.72, major_width: 0.92 },
        place: { label_color: '#617349', label_opacity: 0, halo_color: '#F0ECDE', halo_opacity: 0 },
        poi: { label_color: '#617349', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'midcentury-travel',
    label: 'Mid-Century',
    family: 'Travel poster',
    audience: 'National Park / tourist',
    review_decision: 'keep',
    dark: false,
    background_color: '#E6D2A2',
    label_bg_color: '#19382A',
    label_text_color: '#FAEBC2',
    route_color: '#2A2018',
    water_color: '#83A79D',
    land_color: '#DFC48B',
    base_tile_style: 'carto-light',
    contour_color: '#D8A85F',
    contour_major_color: '#B06A2A',
    font_family: 'Oswald',
    body_font_family: 'Source Sans 3',
    border_style: 'none',
    tile_grain: 0.12,
    composition: 'travel-banner',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 0,
      contour_minor_width: 0.68,
      contour_major_width: 1.34,
      route_width: 5.4,
      pin_color: '#2A2018',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      place_labels_color: '#31442D',
      poi_labels_color: '#31442D',
      atlas_layers: {
        contour: true,
        landcover: false,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#E8CC93', opacity: 0, texture: 'none' },
        water: { fill_color: '#83A79D', fill_opacity: 0.30, waterway_color: '#6E9A94', waterway_opacity: 0.38 },
        waterway: { color: '#6E9A94', opacity: 0.38, width: 0.82 },
        contour: { minor_color: '#D8A85F', major_color: '#B06A2A', minor_opacity: 0.22, major_opacity: 0.58, minor_width: 0.68, major_width: 1.34 },
        place: { label_color: '#31442D', halo_color: '#E6D2A2', halo_opacity: 0.78, label_opacity: 0.34 },
        poi: { label_color: '#31442D', label_opacity: 0.16 },
      },
    }),
  },
  {
    id: 'risograph',
    label: 'Risograph',
    family: 'Print',
    audience: 'Trail marketing / merch',
    review_decision: 'keep',
    dark: false,
    background_color: '#EAE6DB',
    label_bg_color: '#EAE6DB',
    label_text_color: '#16243F',
    route_color: '#FF4F7B',
    water_color: '#2F5FD0',
    land_color: '#EAE6DB',
    base_tile_style: 'carto-light',
    contour_color: '#2F5FD0',
    contour_major_color: '#2F5FD0',
    font_family: 'Big Shoulders Display',
    body_font_family: 'Work Sans',
    border_style: 'none',
    tile_grain: 0.5,
    composition: 'riso-stack',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 3,
      contour_opacity: 0.34,
      contour_minor_width: 0.74,
      contour_major_width: 1.08,
      route_width: 6.2,
      show_start_pin: false,
      show_finish_pin: false,
      tile_effect: 'duotone',
      tile_duotone_strength: 0.82,
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: true,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#EAE6DB', opacity: 0, texture: 'paper' },
        park: { fill_color: '#EAE6DB', opacity: 0, boundary_color: '#2F5FD0', boundary_opacity: 0 },
        water: { fill_color: '#EAE6DB', fill_opacity: 0, waterway_color: '#2F5FD0', waterway_opacity: 0 },
        waterway: { color: '#2F5FD0', opacity: 0, width: 0.9 },
        transportation: { opacity: 0.06, major_color: '#2F5FD0', minor_color: '#2F5FD0', trail_color: '#2F5FD0', show_major: false, show_minor: false, show_trails: false },
        building: { fill_color: '#2F5FD0', opacity: 0 },
        contour: { minor_color: '#2F5FD0', major_color: '#2F5FD0', minor_opacity: 0.46, major_opacity: 0.72, minor_width: 0.74, major_width: 1.08 },
        place: { label_color: '#16243F', label_opacity: 0, halo_color: '#EAE6DB', halo_opacity: 0 },
        poi: { label_color: '#16243F', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    family: 'Technical',
    audience: 'Engineer / surveyor',
    review_decision: 'keep',
    dark: true,
    background_color: '#123F66',
    label_bg_color: '#123F66',
    label_text_color: '#DCEEFF',
    route_color: '#FFD45A',
    water_color: '#123F66',
    land_color: '#123F66',
    base_tile_style: 'carto-dark',
    contour_color: '#9CCDEB',
    contour_major_color: '#E6F4FF',
    font_family: 'Space Grotesk',
    body_font_family: 'IBM Plex Sans',
    border_style: 'thin',
    tile_grain: 0.04,
    composition: 'blueprint-grid',
    show_grid: true,
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade-dark',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      contour_color: '#9CCDEB',
      contour_major_color: '#E6F4FF',
      contour_opacity: 0.24,
      contour_minor_width: 0.46,
      contour_major_width: 0.96,
      route_color: '#FFD45A',
      route_width: 6.4,
      route_opacity: 1,
      route_smooth: 2,
      tile_effect: 'none',
      show_grid: true,
      grid_scope: 'poster',
      grid_opacity: 0.2,
      grid_weight: 1,
      grid_spacing: 5,
      atlas_layers: {
        contour: true,
        landcover: false,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        contour: { minor_color: '#9CCDEB', major_color: '#E6F4FF', minor_opacity: 0.18, major_opacity: 0.58, minor_width: 0.46, major_width: 0.96 },
        landcover: { color: '#123F66', opacity: 0 },
        park: { fill_color: '#123F66', opacity: 0, boundary_color: '#9CCDEB', boundary_opacity: 0 },
        water: { fill_color: '#123F66', fill_opacity: 0, waterway_color: '#9CCDEB', waterway_opacity: 0 },
        waterway: { color: '#9CCDEB', opacity: 0, width: 0.7 },
        transportation: { opacity: 0, major_color: '#9CCDEB', minor_color: '#9CCDEB', trail_color: '#9CCDEB', show_major: false, show_minor: false, show_trails: false },
        building: { fill_color: '#9CCDEB', opacity: 0 },
        place: { label_color: '#DCEEFF', label_opacity: 0, halo_color: '#123F66', halo_opacity: 0 },
        poi: { label_color: '#DCEEFF', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'blueprint-strava',
    label: 'Trail Blueprint',
    family: 'Technical',
    audience: 'Strava ride / data import',
    review_decision: 'revise',
    dark: true,
    background_color: '#07120F',
    label_bg_color: '#07120F',
    label_text_color: '#DDF7EC',
    route_color: '#3DDC97',
    water_color: '#071B16',
    land_color: '#0B1A15',
    base_tile_style: 'carto-dark',
    contour_color: '#3A6A5E',
    contour_major_color: '#91BFAE',
    font_family: 'Space Grotesk',
    body_font_family: 'IBM Plex Sans',
    border_style: 'thin',
    tile_grain: 0.04,
    composition: 'blueprint-strava',
    show_grid: true,
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade-dark',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      route_width: 3,
      tile_effect: 'none',
      show_grid: true,
      grid_scope: 'map',
      grid_opacity: 0.14,
      grid_weight: 1,
      grid_spacing: 8,
      atlas_layer_settings: {
        landcover: { color: '#0B1A15', opacity: 0.94 },
        park: { fill_color: '#0F241D', opacity: 0.18 },
        water: { fill_color: '#071B16', fill_opacity: 0.52, waterway_color: '#1F4F43', waterway_opacity: 0.32 },
        waterway: { color: '#1F4F43', opacity: 0.32, width: 0.8 },
        contour: { minor_color: '#3A6A5E', major_color: '#91BFAE', minor_opacity: 0.34, major_opacity: 0.48 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#DDF7EC', label_opacity: 0, halo_color: '#07120F', halo_opacity: 0 },
        poi: { label_color: '#DDF7EC', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'field-journal',
    label: 'Field Journal',
    family: 'Illustrated',
    audience: 'Hiker / traveler',
    review_decision: 'keep',
    dark: false,
    background_color: '#F2E8D4',
    label_bg_color: '#F2E8D4',
    label_text_color: '#362616',
    route_color: '#6A4A2A',
    water_color: '#A1B6AE',
    land_color: '#E8D9BE',
    base_tile_style: 'maptiler-outdoor',
    contour_color: '#9B8665',
    contour_major_color: '#67563A',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Source Serif 4',
    border_style: 'thin',
    tile_grain: 0.18,
    composition: 'journal-spread',
    map_defaults: mapDefaults({
      preset: 'radmaps-natural',
      show_roads: false,
      show_place_labels: true,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      route_width: 3.85,
      route_opacity: 0.98,
      tile_effect: 'layer-color',
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: true,
        park: true,
        water: true,
        waterway: true,
        transportation: false,
        building: false,
        place: true,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#E8D9BE', opacity: 0.92, texture: 'paper' },
        park: { fill_color: '#B6B181', opacity: 0.18, boundary_color: '#7C6A43', boundary_opacity: 0.20 },
        water: { fill_color: '#A1B6AE', fill_opacity: 0.28, waterway_color: '#7E9C95', waterway_opacity: 0.36 },
        waterway: { color: '#7E9C95', opacity: 0.36, width: 0.9 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        contour: { minor_color: '#9B8665', major_color: '#67563A', minor_opacity: 0.30, major_opacity: 0.42 },
        place: { label_color: '#4C422E', label_opacity: 0.46, halo_color: '#F2E8D4', halo_opacity: 0.70 },
        poi: { label_color: '#4C422E', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'bold-modern',
    label: 'Modernist',
    family: 'Graphic',
    audience: 'Designer / collector',
    review_decision: 'keep',
    dark: false,
    background_color: '#EEECE7',
    label_bg_color: '#D04D40',
    label_text_color: '#060500',
    route_color: '#D04D40',
    water_color: '#211D1A',
    land_color: '#EEECE7',
    base_tile_style: 'carto-light',
    contour_color: '#D9D4CD',
    contour_major_color: '#8B837A',
    font_family: 'Big Shoulders Display',
    body_font_family: 'DM Sans',
    border_style: 'thick',
    tile_grain: 0,
    composition: 'modernist-block',
    map_defaults: mapDefaults({
      preset: 'radmaps-toner-light',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 2,
      route_width: 4.2,
      pin_color: '#D04D40',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      contour_opacity: 0.13,
      contour_minor_width: 0.44,
      contour_major_width: 0.92,
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: false,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#EEECE7', opacity: 0 },
        contour: { minor_color: '#D9D4CD', major_color: '#8B837A', minor_opacity: 0.13, major_opacity: 0.34, minor_width: 0.44, major_width: 0.92 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#191614', label_opacity: 0, halo_color: '#EEECE7', halo_opacity: 0 },
        poi: { label_color: '#191614', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'contour-wash',
    label: 'Contour Wash',
    family: 'Contour study',
    audience: 'Topo art / route keepsake',
    review_decision: 'revise',
    dark: false,
    background_color: '#EBE9E6',
    label_bg_color: '#EBE9E6',
    label_text_color: '#151412',
    route_color: '#151412',
    water_color: '#F2F3EF',
    land_color: '#EBE9E6',
    base_tile_style: 'carto-light',
    contour_color: '#BBB6AE',
    contour_major_color: '#6A655F',
    font_family: 'Space Grotesk',
    body_font_family: 'Source Sans 3',
    border_style: 'thin',
    tile_grain: 0.08,
    composition: 'art-wash',
    map_defaults: mapDefaults({
      preset: 'radmaps-contour-wash',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      route_width: 5.2,
      route_opacity: 0.98,
      show_start_pin: false,
      show_finish_pin: false,
      contour_opacity: 0.48,
      contour_minor_width: 0.62,
      contour_major_width: 0.86,
      padding_factor: 0.08,
      tile_effect: 'none',
      show_grid: false,
      atlas_layer_settings: {
        landcover: { color: '#EBE9E6', opacity: 0.99 },
        park: { fill_color: '#EEECE7', opacity: 0.08 },
        water: { fill_color: '#F2F3EF', fill_opacity: 0.10 },
        waterway: { color: '#D5D2CA', opacity: 0.18, width: 0.66 },
        transportation: { opacity: 0.04, major_color: '#C7C3BB', minor_color: '#D8D5CD', trail_color: '#C7C3BB', show_major: false, show_minor: false, show_trails: false },
        contour: { minor_color: '#BBB6AE', major_color: '#6A655F', minor_opacity: 0.48, major_opacity: 0.58, minor_width: 0.62, major_width: 0.86 },
        place: { label_color: '#7A756E', label_opacity: 0, font_size: 12, halo_color: '#EBE9E6' },
        poi: { label_opacity: 0.10 },
      },
    }),
  },
  {
    id: 'splits-stats',
    label: 'Trail Profile',
    family: 'Data-forward',
    audience: 'Runner / cyclist',
    review_decision: 'revise',
    dark: true,
    background_color: '#0B0D10',
    label_bg_color: '#0B0D10',
    label_text_color: '#F2EFE8',
    route_color: '#FF5A36',
    water_color: '#0E1720',
    land_color: '#141619',
    base_tile_style: 'carto-dark',
    contour_color: '#30343A',
    contour_major_color: '#6A6E73',
    font_family: 'Space Grotesk',
    body_font_family: 'IBM Plex Sans',
    border_style: 'none',
    tile_grain: 0.08,
    composition: 'splits-grid',
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade-dark',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      route_width: 3.45,
      route_opacity: 0.94,
      tile_effect: 'none',
      show_grid: false,
      grid_scope: 'map',
      grid_opacity: 0.10,
      grid_weight: 1,
      grid_spacing: 8,
      show_elevation_profile: true,
      elevation_profile_position: 'separate-band',
      elevation_profile_height: 17,
      elevation_profile_relief: 0.76,
      atlas_layer_settings: {
        landcover: { color: '#141619', opacity: 0.94 },
        park: { fill_color: '#171C20', opacity: 0.18 },
        water: { fill_color: '#0E1720', fill_opacity: 0.54, waterway_color: '#1A2A38', waterway_opacity: 0.34 },
        waterway: { color: '#1A2A38', opacity: 0.34, width: 0.8 },
        contour: { minor_color: '#30343A', major_color: '#6A6E73', minor_opacity: 0.24, major_opacity: 0.28 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#F2EFE8', label_opacity: 0, halo_color: '#0B0D10', halo_opacity: 0 },
        poi: { label_color: '#F2EFE8', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'marathon-bib',
    label: 'Marathon',
    family: 'Commemorative',
    audience: 'Marathon / event',
    review_decision: 'keep',
    dark: false,
    background_color: '#F0EDE5',
    label_bg_color: '#F0EDE5',
    label_text_color: '#14264A',
    route_color: '#E0322C',
    water_color: '#D9E3EA',
    land_color: '#F0ECE2',
    base_tile_style: 'carto-light',
    contour_color: '#D8D0C2',
    contour_major_color: '#A59A86',
    font_family: 'Bebas Neue',
    body_font_family: 'Atkinson Hyperlegible Next',
    border_style: 'thick',
    tile_grain: 0,
    composition: 'bib-numerals',
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      route_width: 4.6,
      pin_color: '#E0322C',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: true,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#F0ECE2', opacity: 0.96 },
        contour: { minor_color: '#D8D0C2', major_color: '#A59A86', minor_opacity: 0.34, major_opacity: 0.44 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#14264A', label_opacity: 0, halo_color: '#F0EDE5', halo_opacity: 0 },
        poi: { label_color: '#14264A', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'dark-sky',
    label: 'Dark Sky',
    family: 'Atmospheric',
    audience: 'Backcountry / dark sky park',
    review_decision: 'keep',
    dark: true,
    background_color: '#070C1E',
    label_bg_color: '#070C1E',
    label_text_color: '#E7ECFB',
    route_color: '#E8C66A',
    water_color: '#071024',
    land_color: '#101A38',
    base_tile_style: 'carto-dark',
    contour_color: '#22325D',
    contour_major_color: '#50689C',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Source Sans 3',
    border_style: 'none',
    tile_grain: 0.22,
    composition: 'darksky-stars',
    map_defaults: mapDefaults({
      preset: 'radmaps-night-relief',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      contour_opacity: 0.22,
      contour_minor_width: 0.56,
      contour_major_width: 0.86,
      route_width: 4.05,
      padding_factor: 0.04,
      show_start_pin: false,
      show_finish_pin: false,
      tile_effect: 'layer-color',
      show_grid: false,
      atlas_layer_settings: {
        landcover: { color: '#101A38', opacity: 0 },
        park: { fill_color: '#101A38', opacity: 0 },
        water: {
          fill_color: '#071024',
          fill_opacity: 0,
          waterway_color: '#18294C',
          waterway_opacity: 0,
          waterway_width: 0.85,
        },
        waterway: { color: '#18294C', opacity: 0, width: 0.85 },
        transportation: {
          major_color: '#28324C',
          minor_color: '#202942',
          road_color: '#202942',
          trail_color: '#F4B942',
          opacity: 0.38,
          show_major: false,
          show_minor: false,
          show_trails: true,
          trail_width: 0.9,
        },
        contour: {
          minor_color: '#22325D',
          major_color: '#50689C',
          minor_opacity: 0.06,
          major_opacity: 0.34,
          minor_width: 0.56,
          major_width: 0.86,
        },
        building: { fill_color: '#111827', opacity: 0 },
        place: {
          label_color: '#D8CFB8',
          label_opacity: 0.24,
          halo_color: '#070C1E',
          font_size: 10,
        },
        poi: { label_color: '#D8CFB8', label_opacity: 0.16 },
      },
    }),
  },
  {
    id: 'botanical',
    label: 'Botanical Plate',
    family: 'Naturalist',
    audience: 'Garden / landscape',
    review_decision: 'keep',
    dark: false,
    background_color: '#EEF1E8',
    label_bg_color: '#EEF1E8',
    label_text_color: '#253721',
    route_color: '#31512B',
    water_color: '#B7C6A8',
    land_color: '#EEF1E8',
    base_tile_style: 'maptiler-outdoor',
    contour_color: '#99A477',
    contour_major_color: '#5D6D3F',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Source Serif 4',
    border_style: 'thin',
    tile_grain: 0.18,
    composition: 'botanical-plate',
    map_defaults: mapDefaults({
      preset: 'radmaps-natural',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 0,
      contour_color: '#8F9F6D',
      contour_major_color: '#536737',
      contour_minor_width: 0.62,
      contour_major_width: 1.32,
      route_width: 4.35,
      route_opacity: 0.94,
      pin_color: '#31512B',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      atlas_layer_settings: {
        landcover: { color: '#EEF1E8', opacity: 0, texture: 'paper' },
        park: { fill_color: '#EEF1E8', opacity: 0, boundary_color: '#6E7A45', boundary_opacity: 0 },
        water: { fill_color: '#EEF1E8', fill_opacity: 0, waterway_color: '#A9B897', waterway_opacity: 0 },
        waterway: { color: '#A9B897', opacity: 0, width: 0.8 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        contour: { minor_color: '#A8B995', major_color: '#536737', minor_opacity: 0.12, major_opacity: 0.72, minor_width: 0.62, major_width: 1.32 },
        place: { label_color: '#253721', label_opacity: 0, halo_color: '#EEF1E8', halo_opacity: 0 },
        poi: { label_color: '#253721', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'brutalist',
    label: 'Brutalist',
    family: 'Concrete',
    audience: 'Urban runner / cyclist',
    review_decision: 'keep',
    dark: false,
    background_color: '#E6E3DD',
    label_bg_color: '#E6E3DD',
    label_text_color: '#010202',
    route_color: '#EA4B23',
    water_color: '#B9B8B0',
    land_color: '#E6E3DD',
    base_tile_style: 'carto-light',
    contour_color: '#BDB9AE',
    contour_major_color: '#010202',
    font_family: 'Bebas Neue',
    body_font_family: 'IBM Plex Sans',
    border_style: 'thick',
    tile_grain: 0.06,
    composition: 'brutalist-slab',
    map_defaults: mapDefaults({
      preset: 'radmaps-toner-light',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      route_width: 5.2,
      route_opacity: 0.96,
      contour_opacity: 0.08,
      contour_minor_width: 0.26,
      contour_major_width: 1.08,
      padding_factor: 0.30,
      tile_effect: 'none',
      show_grid: false,
      show_start_pin: false,
      show_finish_pin: false,
      atlas_layers: {
        contour: true,
        landcover: false,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#E6E3DD', opacity: 0 },
        contour: { minor_color: '#BDB9AE', major_color: '#010202', minor_opacity: 0.07, major_opacity: 0.74, minor_width: 0.26, major_width: 1.08 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#010202', label_opacity: 0, halo_color: '#E6E3DD', halo_opacity: 0 },
        poi: { label_color: '#010202', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'classic-trail',
    label: 'Classic Trail',
    family: 'Heritage',
    audience: 'Trail club / timeless keepsake',
    review_decision: 'merge',
    colorway_of: 'usgs-vintage',
    dark: false,
    background_color: '#EEEEEA',
    label_bg_color: '#EEEEEA',
    label_text_color: '#26313B',
    route_color: '#2F536A',
    water_color: '#BCCAD2',
    land_color: '#EEEEEA',
    base_tile_style: 'carto-light',
    contour_color: '#9FA6AD',
    contour_major_color: '#5F6E7E',
    font_family: 'Libre Baskerville',
    body_font_family: 'Source Sans 3',
    border_style: 'thin',
    tile_grain: 0.18,
    composition: 'park-quad',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      route_width: 3.25,
      route_opacity: 0.94,
      pin_color: '#2F536A',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      place_labels_color: '#40505A',
      poi_labels_color: '#40505A',
      atlas_layers: {
        contour: true,
        landcover: true,
        park: false,
        water: false,
        waterway: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#EEEEEA', opacity: 0.98, texture: 'paper' },
        park: { fill_color: '#EEEEEA', opacity: 0, boundary_color: '#6B7480', boundary_opacity: 0 },
        water: { fill_color: '#EEEEEA', fill_opacity: 0, waterway_color: '#A7B6BE', waterway_opacity: 0 },
        waterway: { color: '#A7B6BE', opacity: 0, width: 0.82 },
        contour: { minor_color: '#9FA6AD', major_color: '#5F6E7E', minor_opacity: 0.52, major_opacity: 0.64, minor_width: 0.66, major_width: 0.86 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#40505A', label_opacity: 0, halo_color: '#EEEEEA', halo_opacity: 0 },
        poi: { label_color: '#40505A', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'ranch-ochre',
    label: 'Ranch Ochre',
    family: 'Western',
    audience: 'Desert / ranch / gravel route',
    review_decision: 'merge',
    colorway_of: 'midcentury-travel',
    dark: false,
    background_color: '#EFDEC0',
    label_bg_color: '#EFDEC0',
    label_text_color: '#3A2414',
    route_color: '#3A2414',
    water_color: '#7EA79C',
    land_color: '#E1BE7F',
    base_tile_style: 'carto-light',
    contour_color: '#A3733C',
    contour_major_color: '#684620',
    font_family: 'Oswald',
    body_font_family: 'Source Sans 3',
    border_style: 'none',
    tile_grain: 0.16,
    composition: 'travel-banner',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      contour_minor_width: 0.68,
      contour_major_width: 1.34,
      route_width: 5.4,
      pin_color: '#3A2414',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: false,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#E9CD95', opacity: 0, texture: 'none' },
        water: { fill_color: '#EFDEC0', fill_opacity: 0, waterway_color: '#A3733C', waterway_opacity: 0 },
        contour: { minor_color: '#A3733C', major_color: '#684620', minor_opacity: 0.20, major_opacity: 0.56, minor_width: 0.68, major_width: 1.34 },
      },
    }),
  },
  {
    id: 'blackline',
    label: 'Blackline',
    family: 'Graphic',
    audience: 'Studio / architecture',
    review_decision: 'merge',
    colorway_of: 'bold-modern',
    dark: false,
    background_color: '#F7F7F4',
    label_bg_color: '#000000',
    label_text_color: '#FFFFFF',
    route_color: '#000000',
    water_color: '#C9C4BA',
    land_color: '#F7F7F4',
    base_tile_style: 'carto-light',
    contour_color: '#777774',
    contour_major_color: '#000000',
    font_family: 'Big Shoulders Display',
    body_font_family: 'IBM Plex Sans',
    border_style: 'thick',
    tile_grain: 0,
    composition: 'modernist-block',
    map_defaults: mapDefaults({
      preset: 'radmaps-toner-light',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 0,
      route_width: 4,
      pin_color: '#000000',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      contour_opacity: 0.14,
      contour_minor_width: 0.62,
      contour_major_width: 1.08,
      tile_effect: 'none',
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: false,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#F7F7F4', opacity: 0 },
        contour: { minor_color: '#777774', major_color: '#000000', minor_opacity: 0.14, major_opacity: 0.86, minor_width: 0.62, major_width: 1.08 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#000000', label_opacity: 0, halo_color: '#F7F7F4', halo_opacity: 0 },
        poi: { label_color: '#000000', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'copper-night',
    label: 'Copper Night',
    family: 'Atmospheric',
    audience: 'Night trail / backcountry',
    review_decision: 'merge',
    colorway_of: 'dark-sky',
    dark: true,
    background_color: '#100B08',
    label_bg_color: '#100B08',
    label_text_color: '#F0D9BF',
    route_color: '#F0B15F',
    water_color: '#1B202A',
    land_color: '#15100C',
    base_tile_style: 'carto-dark',
    contour_color: '#493021',
    contour_major_color: '#9C6741',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Source Sans 3',
    border_style: 'none',
    tile_grain: 0.24,
    composition: 'darksky-stars',
    map_defaults: mapDefaults({
      preset: 'radmaps-night-relief',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 0,
      contour_opacity: 0.16,
      contour_minor_width: 0.58,
      contour_major_width: 1.08,
      route_width: 3.85,
      padding_factor: 0.04,
      composition_footer_distance_unit: 'km',
      composition_footer_date_format: 'month-year',
      show_start_pin: false,
      show_finish_pin: false,
      tile_effect: 'layer-color',
      show_grid: false,
      atlas_layer_settings: {
        landcover: { color: '#15100C', opacity: 0 },
        park: { fill_color: '#15100C', opacity: 0 },
        water: { fill_color: '#1B202A', fill_opacity: 0, waterway_color: '#2E3440', waterway_opacity: 0 },
        waterway: { color: '#2E3440', opacity: 0, width: 0.82 },
        contour: { minor_color: '#493021', major_color: '#9C6741', minor_opacity: 0.085, major_opacity: 0.34, minor_width: 0.58, major_width: 1.08 },
        building: { fill_color: '#15100C', opacity: 0 },
        place: { label_color: '#E9C894', label_opacity: 0.20, halo_color: '#100B08', font_size: 10 },
        poi: { label_color: '#E9C894', label_opacity: 0.12 },
      },
    }),
  },
  {
    id: 'moonstone',
    label: 'Moonstone',
    family: 'Technical',
    audience: 'Clean topo / survey print',
    review_decision: 'merge',
    colorway_of: 'blueprint',
    dark: false,
    background_color: '#EEF0ED',
    label_bg_color: '#EEF0ED',
    label_text_color: '#243238',
    route_color: '#9B4D3A',
    water_color: '#B7C9CC',
    land_color: '#E4E7E1',
    base_tile_style: 'carto-light',
    contour_color: '#B6BFB9',
    contour_major_color: '#687972',
    font_family: 'Space Grotesk',
    body_font_family: 'IBM Plex Sans',
    border_style: 'thin',
    tile_grain: 0.02,
    composition: 'blueprint-grid',
    show_grid: true,
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      contour_minor_width: 0.56,
      contour_major_width: 0.86,
      route_width: 3.55,
      route_opacity: 0.94,
      tile_effect: 'none',
      show_grid: true,
      grid_scope: 'map',
      grid_opacity: 0.075,
      grid_weight: 1,
      grid_spacing: 8,
      atlas_layers: {
        contour: true,
        landcover: false,
        park: false,
        water: false,
        waterway: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        contour: { minor_color: '#B6BFB9', major_color: '#687972', minor_opacity: 0.26, major_opacity: 0.46, minor_width: 0.56, major_width: 0.86 },
        landcover: { color: '#EEF0ED', opacity: 0 },
        park: { fill_color: '#EEF0ED', opacity: 0, boundary_color: '#687972', boundary_opacity: 0 },
        water: { fill_color: '#EEF0ED', fill_opacity: 0, waterway_color: '#B7C9CC', waterway_opacity: 0 },
        waterway: { color: '#B7C9CC', opacity: 0, width: 0.72 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        building: { fill_color: '#B6BFB9', opacity: 0 },
        place: { label_color: '#243238', label_opacity: 0, halo_color: '#EEF0ED', halo_opacity: 0 },
        poi: { label_color: '#243238', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'night-ride',
    label: 'Night Ride',
    family: 'Performance',
    audience: 'MTB / cycling route',
    review_decision: 'merge',
    colorway_of: 'splits-stats',
    dark: true,
    background_color: '#080B0E',
    label_bg_color: '#080B0E',
    label_text_color: '#DFF9FF',
    route_color: '#28D6D6',
    water_color: '#0B1A23',
    land_color: '#101417',
    base_tile_style: 'carto-dark',
    contour_color: '#222F34',
    contour_major_color: '#52666A',
    font_family: 'Oswald',
    body_font_family: 'IBM Plex Sans',
    border_style: 'none',
    tile_grain: 0.1,
    composition: 'splits-grid',
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade-dark',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      route_width: 3.35,
      route_opacity: 0.94,
      tile_effect: 'none',
      show_grid: false,
      show_elevation_profile: true,
      elevation_profile_position: 'separate-band',
      elevation_profile_height: 10,
      elevation_profile_relief: 0.78,
      atlas_layer_settings: {
        landcover: { color: '#101417', opacity: 0.94 },
        park: { fill_color: '#132026', opacity: 0.18 },
        water: { fill_color: '#0B1A23', fill_opacity: 0.54, waterway_color: '#18313A', waterway_opacity: 0.34 },
        waterway: { color: '#18313A', opacity: 0.34, width: 0.8 },
        contour: { minor_color: '#222F34', major_color: '#52666A', minor_opacity: 0.32, major_opacity: 0.48 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#DFF9FF', label_opacity: 0, halo_color: '#080B0E', halo_opacity: 0 },
        poi: { label_color: '#DFF9FF', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'daybreak-trace',
    label: 'Daybreak',
    family: 'Travel poster',
    audience: 'Sunny trail / family hike',
    review_decision: 'merge',
    colorway_of: 'midcentury-travel',
    dark: false,
    background_color: '#F4D8CF',
    label_bg_color: '#F4D8CF',
    label_text_color: '#3A2630',
    route_color: '#3A2630',
    water_color: '#F4D8CF',
    land_color: '#F4D8CF',
    base_tile_style: 'carto-light',
    contour_color: '#E19A82',
    contour_major_color: '#BE624A',
    font_family: 'Oswald',
    body_font_family: 'Source Sans 3',
    border_style: 'none',
    tile_grain: 0.1,
    composition: 'travel-banner',
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 1,
      contour_opacity: 0.16,
      contour_minor_width: 0.34,
      contour_major_width: 0.72,
      route_width: 5.0,
      route_opacity: 0.94,
      pin_color: '#3A2630',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'none',
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: false,
        water: false,
        waterway: false,
        park: false,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#F4D8CF', opacity: 0, texture: 'none' },
        water: { fill_color: '#F4D8CF', fill_opacity: 0, waterway_color: '#E19A82', waterway_opacity: 0 },
        contour: { minor_color: '#E19A82', major_color: '#BE624A', minor_opacity: 0.10, major_opacity: 0.64, minor_width: 0.34, major_width: 0.72 },
      },
    }),
  },
  {
    id: 'electric-atlas',
    label: 'Electric Atlas',
    family: 'Data-forward',
    audience: 'High-energy ride / run',
    review_decision: 'revise',
    dark: true,
    background_color: '#0A0A11',
    label_bg_color: '#0A0A11',
    label_text_color: '#B8B6F4',
    route_color: '#FA498E',
    water_color: '#08172A',
    land_color: '#0B0E1A',
    base_tile_style: 'carto-dark',
    contour_color: '#4A49A2',
    contour_major_color: '#7772EA',
    font_family: 'Big Shoulders Display',
    body_font_family: 'IBM Plex Sans',
    border_style: 'thin',
    tile_grain: 0.08,
    composition: 'blueprint-strava',
    show_grid: true,
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade-dark',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      route_width: 4.2,
      show_start_pin: false,
      show_finish_pin: false,
      tile_effect: 'none',
      show_grid: true,
      grid_scope: 'map',
      grid_opacity: 0.16,
      grid_weight: 1,
      grid_spacing: 6,
      atlas_layer_settings: {
        landcover: { color: '#0B0E1A', opacity: 0.96 },
        park: { fill_color: '#10152C', opacity: 0.20 },
        water: { fill_color: '#08172A', fill_opacity: 0.50, waterway_color: '#182A56', waterway_opacity: 0.34 },
        waterway: { color: '#182A56', opacity: 0.34, width: 0.82 },
        contour: { minor_color: '#4A49A2', major_color: '#7772EA', minor_opacity: 0.44, major_opacity: 0.62 },
        transportation: { opacity: 0, show_major: false, show_minor: false, show_trails: false },
        place: { label_color: '#B8B6F4', label_opacity: 0, halo_color: '#0A0A11', halo_opacity: 0 },
        poi: { label_color: '#B8B6F4', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'cartouche-place',
    label: 'Cartouche',
    family: 'Place portrait',
    audience: 'Place portrait / no-route map',
    review_decision: 'new',
    dark: false,
    background_color: '#E2E2D9',
    label_bg_color: '#E2E2D9',
    label_text_color: '#0F121A',
    route_color: '#9A3B27',
    water_color: '#D2D8CE',
    land_color: '#E2E2D9',
    base_tile_style: 'carto-light',
    contour_color: '#C9C2B2',
    contour_major_color: '#7A6E55',
    font_family: 'Playfair Display',
    body_font_family: 'Source Serif 4',
    border_style: 'thin',
    tile_grain: 0.12,
    composition: 'place-frame',
    show_grid: false,
    map_defaults: mapDefaults({
      preset: 'radmaps-alidade',
      show_roads: true,
      roads_color: '#AFA68F',
      roads_opacity: 0.28,
      show_place_labels: false,
      place_labels_color: '#5C513F',
      place_labels_opacity: 0,
      show_poi_labels: false,
      poi_labels_color: '#6F604A',
      poi_labels_opacity: 0,
      show_hillshade: false,
      show_contours: false,
      route_width: 2.8,
      route_opacity: 0.86,
      show_primary_route: false,
      show_start_pin: false,
      show_finish_pin: false,
      show_grid: true,
      grid_scope: 'map',
      grid_opacity: 0.28,
      grid_weight: 1.25,
      grid_spacing: 8,
      tile_effect: 'none',
      atlas_layer_settings: {
        landcover: { color: '#E2E2D9', opacity: 0.98, texture: 'paper' },
        park: { fill_color: '#D2D0C1', opacity: 0.10, boundary_color: '#8F8874', boundary_opacity: 0.12 },
        water: { fill_color: '#D2D8CE', fill_opacity: 0.42, waterway_color: '#B3BDAF', waterway_opacity: 0.30 },
        waterway: { color: '#B3BDAF', opacity: 0.30, width: 0.72 },
        transportation: { opacity: 0.28, major_color: '#817762', minor_color: '#A49B84', trail_color: '#8F8874', show_major: true, show_minor: true, show_trails: false, major_width: 1.15, minor_width: 0.58 },
        building: { fill_color: '#C7C2B1', opacity: 0.035 },
        place: { label_color: '#5C513F', label_opacity: 0, halo_color: '#E2E2D9', halo_opacity: 0 },
        poi: { label_color: '#6F604A', label_opacity: 0 },
      },
    }),
  },
  {
    id: 'sea-chart',
    label: 'Sea Chart',
    family: 'Nautical',
    audience: 'Waterfront / coastal route',
    review_decision: 'new',
    dark: false,
    background_color: '#E4EDE7',
    label_bg_color: '#E4EDE7',
    label_text_color: '#1D2A36',
    route_color: '#A6245D',
    water_color: '#C7DDD7',
    land_color: '#E4EDE7',
    base_tile_style: 'carto-light',
    contour_color: '#6C9A8F',
    contour_major_color: '#2B625A',
    font_family: 'Libre Baskerville',
    body_font_family: 'IBM Plex Sans',
    border_style: 'thin',
    tile_grain: 0.08,
    composition: 'sea-chart',
    show_grid: false,
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      show_place_labels: false,
      place_labels_color: '#315C65',
      place_labels_opacity: 0,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 0,
      contour_opacity: 0.42,
      contour_minor_width: 0.72,
      contour_major_width: 1.05,
      route_color: '#A6245D',
      route_width: 3.5,
      route_opacity: 0.96,
      show_start_pin: false,
      show_finish_pin: false,
      show_grid: false,
      grid_scope: 'map',
      grid_opacity: 0.08,
      grid_weight: 1,
      grid_spacing: 12,
      tile_effect: 'none',
      atlas_layer_settings: {
        landcover: { color: '#E4EDE7', opacity: 0.99 },
        water: { fill_color: '#C7DDD7', fill_opacity: 0.56, waterway_color: '#5F9286', waterway_opacity: 0.48 },
        waterway: { color: '#5F9286', opacity: 0.48, width: 1.05 },
        transportation: { opacity: 0.12, show_major: false, show_minor: false, show_trails: false },
        contour: { minor_color: '#6C9A8F', major_color: '#2B625A', minor_opacity: 0.42, major_opacity: 0.58, minor_width: 0.72, major_width: 1.05 },
        place: { label_color: '#315C65', label_opacity: 0, halo_color: '#E4EDE7' },
        poi: { label_opacity: 0.14 },
      },
    }),
  },
  {
    id: 'relief-shaded',
    label: 'Shaded Relief',
    family: 'Terrain',
    audience: 'Mountain / terrain print',
    review_decision: 'new',
    dark: false,
    background_color: '#ECE4D3',
    label_bg_color: '#ECE4D3',
    label_text_color: '#27231D',
    route_color: '#14110D',
    water_color: '#B9C2B0',
    land_color: '#E9D8B8',
    base_tile_style: 'maptiler-topo',
    contour_color: '#C2AF86',
    contour_major_color: '#8B704B',
    font_family: 'Newsreader',
    body_font_family: 'Source Sans 3',
    border_style: 'thin',
    tile_grain: 0.10,
    composition: 'editorial-tall',
    map_defaults: mapDefaults({
      preset: 'radmaps-natural',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: true,
      hillshade_intensity: 0.14,
      hillshade_highlight: 0.18,
      show_contours: true,
      contour_detail: 3,
      contour_opacity: 0.38,
      contour_minor_width: 0.48,
      contour_major_width: 1.04,
      route_color: '#14110D',
      route_width: 5.1,
      route_opacity: 0.96,
      pin_color: '#14110D',
      pin_opacity: 1,
      show_start_pin: true,
      show_finish_pin: true,
      tile_effect: 'layer-color',
      show_grid: false,
      atlas_layer_settings: {
        landcover: { color: '#E9D8B8', opacity: 0.82, texture: 'relief' },
        park: { fill_color: '#DCC391', opacity: 0.12 },
        water: { fill_color: '#C9C5A8', fill_opacity: 0.12, waterway_color: '#B5AE91', waterway_opacity: 0.16 },
        waterway: { color: '#B5AE91', opacity: 0.16, width: 0.68 },
        contour: { minor_color: '#C2AF86', major_color: '#8B704B', minor_opacity: 0.30, major_opacity: 0.48, minor_width: 0.48, major_width: 1.04 },
      },
    }),
  },
  {
    id: 'transit-diagram',
    label: 'Transit',
    family: 'Diagrammatic',
    audience: 'Tour / stops itinerary',
    review_decision: 'new',
    dark: false,
    background_color: '#F7F5F0',
    label_bg_color: '#F7F5F0',
    label_text_color: '#181818',
    route_color: '#7A1FA2',
    water_color: '#D8E5E7',
    land_color: '#F7F5F0',
    base_tile_style: 'carto-light',
    contour_color: '#D4D1C9',
    contour_major_color: '#1F8A5B',
    font_family: 'Outfit',
    body_font_family: 'IBM Plex Sans',
    border_style: 'none',
    tile_grain: 0,
    composition: 'transit-diagram',
    show_grid: false,
    map_defaults: mapDefaults({
      preset: 'radmaps-simple-contour',
      show_roads: false,
      roads_color: '#D8D4CB',
      roads_opacity: 0,
      show_place_labels: false,
      place_labels_color: '#6F746F',
      place_labels_opacity: 0,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: false,
      route_color: '#7A1FA2',
      route_width: 7,
      route_opacity: 0.96,
      route_smooth: 2,
      show_start_pin: false,
      show_finish_pin: false,
      show_grid: true,
      grid_scope: 'map',
      grid_opacity: 0.09,
      grid_weight: 1,
      grid_spacing: 8,
      tile_effect: 'none',
      atlas_layers: {
        contour: false,
        landcover: true,
        water: true,
        waterway: true,
        park: true,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#F7F5F0', opacity: 0.98 },
        water: { fill_color: '#D8E5E7', fill_opacity: 0.24, waterway_color: '#BCCFD2', waterway_opacity: 0.18 },
        waterway: { color: '#BCCFD2', opacity: 0.18, width: 0.8 },
        transportation: { opacity: 0, major_color: '#D0CDC4', minor_color: '#E1DFD8', trail_color: '#D0CDC4', show_major: false, show_minor: false, show_trails: false },
        contour: { minor_opacity: 0, major_opacity: 0 },
        place: { label_color: '#6F746F', label_opacity: 0, halo_color: '#F7F5F0', halo_opacity: 0.85 },
        poi: { label_opacity: 0 },
      },
    }),
  },
  {
    id: 'plein-air',
    label: 'Plein Air',
    family: 'Painterly',
    audience: 'Sentimental trip print',
    review_decision: 'new',
    dark: false,
    background_color: '#F6F1E8',
    label_bg_color: '#F6F1E8',
    label_text_color: '#33302A',
    route_color: '#C2683F',
    water_color: '#A9C2B4',
    land_color: '#F3EDE1',
    base_tile_style: 'carto-light',
    contour_color: '#C0B59A',
    contour_major_color: '#8A7D63',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Source Sans 3',
    border_style: 'thin',
    tile_grain: 0.18,
    composition: 'art-wash',
    map_defaults: mapDefaults({
      preset: 'radmaps-watercolor-paper',
      show_roads: false,
      show_place_labels: false,
      show_poi_labels: false,
      show_hillshade: false,
      show_contours: true,
      contour_detail: 5,
      contour_opacity: 0.36,
      contour_minor_width: 0.72,
      contour_major_width: DEFAULT_CONTOUR_MAJOR_WIDTH,
      route_width: 3.6,
      show_start_pin: false,
      show_finish_pin: false,
      tile_effect: 'none',
      show_grid: false,
      atlas_layers: {
        contour: true,
        landcover: true,
        park: true,
        water: true,
        waterway: true,
        transportation: false,
        building: false,
        place: false,
        poi: false,
      },
      atlas_layer_settings: {
        landcover: { color: '#E6D7BB', opacity: 0.88, texture: 'paper' },
        park: { fill_color: '#A9C2B4', opacity: 0.22 },
        water: { fill_color: '#A9C2B4', fill_opacity: 0.26 },
        waterway: { color: '#A9C2B4', opacity: 0.32, width: 0.9 },
        transportation: { opacity: 0.10, show_major: false, show_minor: false, show_trails: false },
        contour: { minor_color: '#C0B59A', major_color: '#8A7D63', minor_opacity: 0.36, major_opacity: 0.44 },
        place: { label_color: '#6A5E4D', label_opacity: 0.16, halo_color: '#F3EDE1' },
        poi: { label_color: '#6A5E4D', label_opacity: 0 },
      },
    }),
  },
] as const satisfies readonly RefinedThemeRecipe[]

export const REFINED_THEMES = REFINED_THEME_RECIPES.map(withEditableDefaults)

export const REFINED_THEME_IDS = REFINED_THEMES.map(theme => theme.id) as ColorTheme[]
export const ALL_COLOR_THEME_IDS = Array.from(new Set([...COLOR_THEMES.map(theme => theme.id), ...REFINED_THEME_IDS])) as ColorTheme[]

export const LEGACY_THEME_MIGRATION_TARGETS = Object.fromEntries(
  COLOR_THEMES
    .filter(theme => theme.legacy && theme.migration_target)
    .map(theme => [theme.id, theme.migration_target]),
) as Partial<Record<ColorTheme, ColorTheme>>

export function getRefinedThemeById(id: ColorTheme | string): RefinedThemeDefinition | undefined {
  return REFINED_THEMES.find(theme => theme.id === id)
}

export function getThemeDefinition(id: ColorTheme | string): ThemeDefinition | undefined {
  return getRefinedThemeById(id) ?? COLOR_THEMES.find(theme => theme.id === id)
}
