import { COLOR_THEMES, type ColorTheme, type CompositionId, type StyleConfig, type ThemeDefinition } from '~/types'

export const COMPOSITION_IDS = [
  'editorial-tall',
  'park-quad',
  'travel-banner',
  'riso-stack',
  'blueprint-grid',
  'blueprint-strava',
  'journal-spread',
  'modernist-block',
  'splits-grid',
  'bib-numerals',
  'darksky-stars',
  'botanical-plate',
  'brutalist-slab',
] as const satisfies readonly CompositionId[]

type RefinedThemeDefinition = ThemeDefinition & {
  composition: CompositionId
  audience: string
  family: string
  map_defaults: Partial<StyleConfig>
}

function mapDefaults(defaults: Partial<StyleConfig>): Partial<StyleConfig> {
  return defaults
}

export const REFINED_THEMES = [
  {
    id: 'editorial-minimal',
    label: 'Editorial',
    family: 'Minimal',
    audience: 'Gallery / collector',
    dark: false,
    background_color: '#F6F2EA',
    label_bg_color: '#F6F2EA',
    label_text_color: '#171513',
    route_color: '#B5251D',
    water_color: '#D6DCE0',
    land_color: '#EFE9DD',
    base_tile_style: 'carto-light',
    contour_color: '#CFC6B6',
    contour_major_color: '#A89C86',
    font_family: 'Playfair Display',
    body_font_family: 'Libre Baskerville',
    border_style: 'none',
    tile_grain: 0,
    composition: 'editorial-tall',
    map_defaults: mapDefaults({ preset: 'contour-art', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'usgs-vintage',
    label: 'USGS',
    family: 'Topographic',
    audience: 'National Park / tourist',
    dark: false,
    background_color: '#EDE3CC',
    label_bg_color: '#EDE3CC',
    label_text_color: '#3A2A14',
    route_color: '#B43A1F',
    water_color: '#9CB7C0',
    land_color: '#E8DCBE',
    base_tile_style: 'maptiler-topo',
    contour_color: '#9C7A48',
    contour_major_color: '#6B4D26',
    font_family: 'DM Serif Display',
    body_font_family: 'Libre Baskerville',
    border_style: 'thin',
    tile_grain: 0.32,
    composition: 'park-quad',
    map_defaults: mapDefaults({ preset: 'natural-topo', show_roads: false, show_place_labels: true, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'midcentury-travel',
    label: 'Mid-Century',
    family: 'Travel poster',
    audience: 'National Park / tourist',
    dark: false,
    background_color: '#E8DAB8',
    label_bg_color: '#1F3325',
    label_text_color: '#F0E5C5',
    route_color: '#D4603A',
    water_color: '#7FA098',
    land_color: '#D8C594',
    base_tile_style: 'carto-light',
    contour_color: '#B89060',
    contour_major_color: '#7A5830',
    font_family: 'Oswald',
    body_font_family: 'Work Sans',
    border_style: 'none',
    tile_grain: 0.12,
    composition: 'travel-banner',
    map_defaults: mapDefaults({ preset: 'contour-art', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'risograph',
    label: 'Risograph',
    family: 'Print',
    audience: 'Trail marketing / merch',
    dark: false,
    background_color: '#F2EAD2',
    label_bg_color: '#F2EAD2',
    label_text_color: '#1A1F45',
    route_color: '#E84A2A',
    water_color: '#3F6FB8',
    land_color: '#E8DDB8',
    base_tile_style: 'carto-light',
    contour_color: '#3F6FB8',
    contour_major_color: '#1A1F45',
    font_family: 'Oswald',
    body_font_family: 'Space Grotesk',
    border_style: 'none',
    tile_grain: 0.40,
    composition: 'riso-stack',
    map_defaults: mapDefaults({ preset: 'minimalist', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'duotone', show_grid: false }),
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    family: 'Technical',
    audience: 'Engineer / surveyor',
    dark: true,
    background_color: '#0F2D52',
    label_bg_color: '#0F2D52',
    label_text_color: '#D0E4FF',
    route_color: '#FFD046',
    water_color: '#091F3A',
    land_color: '#143664',
    base_tile_style: 'carto-dark',
    contour_color: '#3D7AC2',
    contour_major_color: '#7CB0E8',
    font_family: 'Space Grotesk',
    body_font_family: 'Space Grotesk',
    border_style: 'thin',
    tile_grain: 0.04,
    composition: 'blueprint-grid',
    show_grid: true,
    map_defaults: mapDefaults({ preset: 'route-only', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: true, grid_scope: 'poster', grid_opacity: 0.2, grid_weight: 1 }),
  },
  {
    id: 'blueprint-strava',
    label: 'Blueprint · Strava',
    family: 'Technical',
    audience: 'Strava ride / data import',
    dark: true,
    background_color: '#0F2D52',
    label_bg_color: '#0F2D52',
    label_text_color: '#D0E4FF',
    route_color: '#FC4C02',
    water_color: '#091F3A',
    land_color: '#143664',
    base_tile_style: 'carto-dark',
    contour_color: '#3D7AC2',
    contour_major_color: '#7CB0E8',
    font_family: 'Space Grotesk',
    body_font_family: 'Space Grotesk',
    border_style: 'thin',
    tile_grain: 0.04,
    composition: 'blueprint-strava',
    show_grid: true,
    map_defaults: mapDefaults({ preset: 'route-only', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: true, grid_scope: 'poster', grid_opacity: 0.2, grid_weight: 1 }),
  },
  {
    id: 'field-journal',
    label: 'Journal',
    family: 'Illustrated',
    audience: 'Hiker / traveler',
    dark: false,
    background_color: '#F1E9D8',
    label_bg_color: '#F1E9D8',
    label_text_color: '#3A2A1A',
    route_color: '#A23B26',
    water_color: '#A8B8B0',
    land_color: '#EBE0C8',
    base_tile_style: 'maptiler-outdoor',
    contour_color: '#9C8868',
    contour_major_color: '#6E5C3E',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Libre Baskerville',
    border_style: 'thin',
    tile_grain: 0.22,
    composition: 'journal-spread',
    map_defaults: mapDefaults({ preset: 'natural-topo', show_roads: false, show_place_labels: true, show_hillshade: true, show_contours: true, contour_detail: 5, tile_effect: 'layer-color', show_grid: false }),
  },
  {
    id: 'bold-modern',
    label: 'Modernist',
    family: 'Graphic',
    audience: 'Designer / collector',
    dark: false,
    background_color: '#F1EAE0',
    label_bg_color: '#1C1917',
    label_text_color: '#F1EAE0',
    route_color: '#FF3A2E',
    water_color: '#1C1917',
    land_color: '#F1EAE0',
    base_tile_style: 'carto-light',
    contour_color: '#A8A29E',
    contour_major_color: '#1C1917',
    font_family: 'Big Shoulders Display',
    body_font_family: 'DM Sans',
    border_style: 'thick',
    tile_grain: 0,
    composition: 'modernist-block',
    map_defaults: mapDefaults({ preset: 'route-only', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: false, tile_effect: 'duotone', show_grid: false }),
  },
  {
    id: 'splits-stats',
    label: 'Splits',
    family: 'Data-forward',
    audience: 'Runner / cyclist',
    dark: true,
    background_color: '#0E0E10',
    label_bg_color: '#0E0E10',
    label_text_color: '#F4F2EE',
    route_color: '#FC4C02',
    water_color: '#101820',
    land_color: '#161618',
    base_tile_style: 'carto-dark',
    contour_color: '#2A2A2E',
    contour_major_color: '#56565E',
    font_family: 'Space Grotesk',
    body_font_family: 'Space Grotesk',
    border_style: 'none',
    tile_grain: 0.08,
    composition: 'splits-grid',
    map_defaults: mapDefaults({ preset: 'road-network', show_roads: true, show_place_labels: false, show_hillshade: false, show_contours: false, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'marathon-bib',
    label: 'Marathon',
    family: 'Commemorative',
    audience: 'Marathon / event',
    dark: false,
    background_color: '#FAFAF7',
    label_bg_color: '#FAFAF7',
    label_text_color: '#0A0A0A',
    route_color: '#1A4D8F',
    water_color: '#D8E2EC',
    land_color: '#F0EDE7',
    base_tile_style: 'carto-light',
    contour_color: '#D6CFC2',
    contour_major_color: '#A39A88',
    font_family: 'Bebas Neue',
    body_font_family: 'DM Sans',
    border_style: 'thick',
    tile_grain: 0,
    composition: 'bib-numerals',
    map_defaults: mapDefaults({ preset: 'road-network', show_roads: true, show_place_labels: false, show_hillshade: false, show_contours: false, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'dark-sky',
    label: 'Dark Sky',
    family: 'Atmospheric',
    audience: 'Backcountry / dark sky park',
    dark: true,
    background_color: '#0A0F1C',
    label_bg_color: '#0A0F1C',
    label_text_color: '#E6E1D2',
    route_color: '#F4B942',
    water_color: '#06091A',
    land_color: '#10162B',
    base_tile_style: 'carto-dark',
    contour_color: '#2D3E64',
    contour_major_color: '#5C7AA8',
    font_family: 'Fjalla One',
    body_font_family: 'Work Sans',
    border_style: 'none',
    tile_grain: 0.18,
    composition: 'darksky-stars',
    map_defaults: mapDefaults({ preset: 'contour-art', show_roads: false, show_place_labels: false, show_hillshade: true, show_contours: true, contour_detail: 5, tile_effect: 'layer-color', show_grid: false }),
  },
  {
    id: 'botanical',
    label: 'Botanical',
    family: 'Naturalist',
    audience: 'Garden / landscape',
    dark: false,
    background_color: '#EDE6D6',
    label_bg_color: '#EDE6D6',
    label_text_color: '#2A3A28',
    route_color: '#7B3A2A',
    water_color: '#A6BFA6',
    land_color: '#E2DCC4',
    base_tile_style: 'maptiler-outdoor',
    contour_color: '#9CA77A',
    contour_major_color: '#5E6E3E',
    font_family: 'Cormorant Garamond',
    body_font_family: 'Libre Baskerville',
    border_style: 'thin',
    tile_grain: 0.10,
    composition: 'botanical-plate',
    map_defaults: mapDefaults({ preset: 'natural-topo', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
  {
    id: 'brutalist',
    label: 'Brutalist',
    family: 'Concrete',
    audience: 'Urban runner / cyclist',
    dark: false,
    background_color: '#E5E1D8',
    label_bg_color: '#E5E1D8',
    label_text_color: '#0A0A0A',
    route_color: '#FF1F1F',
    water_color: '#B8B8B0',
    land_color: '#D8D4CB',
    base_tile_style: 'carto-light',
    contour_color: '#9A968E',
    contour_major_color: '#4C4844',
    font_family: 'Bebas Neue',
    body_font_family: 'Space Grotesk',
    border_style: 'thick',
    tile_grain: 0.06,
    composition: 'brutalist-slab',
    map_defaults: mapDefaults({ preset: 'contour-art', show_roads: false, show_place_labels: false, show_hillshade: false, show_contours: true, contour_detail: 5, tile_effect: 'none', show_grid: false }),
  },
] as const satisfies readonly RefinedThemeDefinition[]

export const REFINED_THEME_IDS = REFINED_THEMES.map(theme => theme.id) as ColorTheme[]
export const ALL_COLOR_THEME_IDS = Array.from(new Set([...COLOR_THEMES.map(theme => theme.id), ...REFINED_THEME_IDS])) as ColorTheme[]

export const LEGACY_THEME_MIGRATION_TARGETS = Object.fromEntries(
  COLOR_THEMES
    .filter(theme => theme.legacy && theme.migration_target)
    .map(theme => [theme.id, theme.migration_target]),
) as Partial<Record<ColorTheme, ColorTheme>>

export function getRefinedThemeById(id: ColorTheme | string): RefinedThemeDefinition | undefined {
  return REFINED_THEMES.find(theme => theme.id === id)
}

export function getThemeDefinition(id: ColorTheme | string): ThemeDefinition | undefined {
  return getRefinedThemeById(id) ?? COLOR_THEMES.find(theme => theme.id === id)
}
