import type { ColorTheme, CompositionId, FontFamily } from '~/types'

export type ThemeSpecDecision = 'keep' | 'merge' | 'revise' | 'new'
export type ThemeSpecPriority = 'anchor' | 'normal'
export type ThemeCaseBehavior = 'title' | 'upper'
export type ThemeSpecMonoFont = FontFamily | 'IBM Plex Mono'

export interface ThemeSpecContract {
  id: ColorTheme
  label: string
  decision: ThemeSpecDecision
  priority: ThemeSpecPriority
  composition: CompositionId
  contentFixture: string
  titleFont: FontFamily
  bodyFont: FontFamily
  monoFont?: ThemeSpecMonoFont
  caseBehavior: ThemeCaseBehavior
  palette: {
    paper: string
    ink: string
    sub: string
    line: string
    accent: string
    accent2?: string
    mapBg: string
  }
  mapStyleRequirements: string[]
  routeStyleRequirements: string[]
  requiredLayoutFeatures: string[]
  problem: string
  refinement: string
  mergeTarget?: ColorTheme
  notImplemented: string[]
}

export const THEME_SPEC_CONTRACTS: readonly ThemeSpecContract[] = [
  {
    id: 'editorial-minimal',
    label: 'Editorial',
    decision: 'keep',
    priority: 'anchor',
    composition: 'editorial-tall',
    contentFixture: 'rainier',
    titleFont: 'Playfair Display',
    bodyFont: 'Source Serif 4',
    caseBehavior: 'title',
    palette: { paper: '#f6f3ec', ink: '#1c1a17', sub: '#6f685c', line: '#cfc7b6', accent: '#9a3b27', mapBg: '#efeadf' },
    mapStyleRequirements: ['quiet simple contours', 'warm paper map field', 'hairline rule language'],
    routeStyleRequirements: ['single rust accent route', 'route remains the subject on quiet contours'],
    requiredLayoutFeatures: ['gallery grid', 'about 64 percent map', 'single accent'],
    problem: 'Strong already, but title/map ratio drifts and the route can vanish on quiet contour.',
    refinement: 'Tightened to a true gallery grid: 64% map, hairline rule, single accent. Route weight up for subject clarity.',
    notImplemented: [],
  },
  {
    id: 'usgs-vintage',
    label: 'USGS Heritage',
    decision: 'keep',
    priority: 'anchor',
    composition: 'park-quad',
    contentFixture: 'whitney',
    titleFont: 'Libre Baskerville',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'upper',
    palette: { paper: '#efe9d8', ink: '#23301f', sub: '#5c6b4f', line: '#9aa987', accent: '#7a4a2a', mapBg: '#f3eedd' },
    mapStyleRequirements: ['full quad treatment', 'cream paper', 'tan contours', 'green index contours'],
    routeStyleRequirements: ['rust red route', 'clean halo', 'endpoint markers'],
    requiredLayoutFeatures: ['inset map neatline', 'corner coordinate ticks', 'classic bottom collar', 'large uppercase title'],
    problem: 'Reads generic-vintage; corner data and quad framing under-used; contour too brown-muddy.',
    refinement: 'Full quad treatment: inset neatline, corner coordinate ticks, green index contours, classic bottom collar.',
    notImplemented: [],
  },
  {
    id: 'classic-trail',
    label: 'Classic Trail',
    decision: 'merge',
    priority: 'normal',
    composition: 'park-quad',
    contentFixture: 'scotland',
    titleFont: 'Libre Baskerville',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'upper',
    palette: { paper: '#e9e9e4', ink: '#1f2630', sub: '#56606c', line: '#8e97a3', accent: '#37526b', mapBg: '#eeeeea' },
    mapStyleRequirements: ['same USGS Heritage composition', 'cool slate palette'],
    routeStyleRequirements: ['slate route', 'clean halo', 'endpoint markers'],
    requiredLayoutFeatures: ['same park quad layout as USGS Heritage'],
    problem: 'Identical composition, fonts and map preset to USGS Heritage - a true duplicate.',
    refinement: "Fold into USGS Heritage as the 'Slate' colorway (cool blue-grey neatline) rather than a separate theme.",
    mergeTarget: 'usgs-vintage',
    notImplemented: [],
  },
  {
    id: 'midcentury-travel',
    label: 'Mid-Century',
    decision: 'keep',
    priority: 'anchor',
    composition: 'travel-banner',
    contentFixture: 'dolomites',
    titleFont: 'Oswald',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'upper',
    palette: { paper: '#f4ead3', ink: '#2a2018', sub: '#7a5d3a', line: '#d8b27a', accent: '#c4561f', mapBg: '#f0dcae' },
    mapStyleRequirements: ['simple contour terrain', 'two-color print feel', 'sun arc behind terrain'],
    routeStyleRequirements: ['dark ink route', 'clean halo', 'endpoint markers'],
    requiredLayoutFeatures: ['travel-poster banner', 'condensed uppercase title', 'spec map/banner proportions'],
    problem: 'Banner type weak vs the genre; arc/sun motif missing; palette too safe.',
    refinement: 'Travel-poster banner with a setting-sun arc behind terrain, condensed all-caps title, two-color print look.',
    notImplemented: [],
  },
  {
    id: 'ranch-ochre',
    label: 'Ranch Ochre',
    decision: 'merge',
    priority: 'normal',
    composition: 'travel-banner',
    contentFixture: 'moab',
    titleFont: 'Oswald',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'upper',
    palette: { paper: '#f0e2c4', ink: '#3a2414', sub: '#8a6334', line: '#d2a154', accent: '#a8551d', mapBg: '#ecd3a0' },
    mapStyleRequirements: ['Mid-Century layout', 'warm desert ochre palette'],
    routeStyleRequirements: ['dark ink route', 'clean halo'],
    requiredLayoutFeatures: ['same travel-banner layout as Mid-Century'],
    problem: 'Same Oswald + travel-banner as Mid-Century, only re-coloured ochre.',
    refinement: "Demote to a Mid-Century colorway ('Ochre'): warm desert palette, same composition.",
    mergeTarget: 'midcentury-travel',
    notImplemented: [],
  },
  {
    id: 'daybreak-trace',
    label: 'Daybreak',
    decision: 'merge',
    priority: 'normal',
    composition: 'travel-banner',
    contentFixture: 'napa',
    titleFont: 'Oswald',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'upper',
    palette: { paper: '#f7e8e0', ink: '#3a2630', sub: '#9a6a72', line: '#e6b8a8', accent: '#d06a52', mapBg: '#f6ddd0' },
    mapStyleRequirements: ['Mid-Century layout', 'dawn palette'],
    routeStyleRequirements: ['dark ink route', 'clean halo'],
    requiredLayoutFeatures: ['same travel-banner layout as Mid-Century'],
    problem: 'A third travel-banner theme; Playfair title fights the condensed-poster genre.',
    refinement: "Merge as Mid-Century 'Daybreak' colorway (dawn pinks); drop the serif title - keep one banner face.",
    mergeTarget: 'midcentury-travel',
    notImplemented: [],
  },
  {
    id: 'risograph',
    label: 'Risograph',
    decision: 'keep',
    priority: 'normal',
    composition: 'riso-stack',
    contentFixture: 'rainier',
    titleFont: 'Big Shoulders Display',
    bodyFont: 'Work Sans',
    caseBehavior: 'upper',
    palette: { paper: '#f3efe2', ink: '#16243f', sub: '#4a4636', line: '#16243f', accent: '#ff4f7b', accent2: '#2f5fd0', mapBg: '#f4f0e3' },
    mapStyleRequirements: ['two-ink print feel', 'blue contours', 'paper grain'],
    routeStyleRequirements: ['fluoro pink route', 'blue misregistration offset', 'no endpoint markers'],
    requiredLayoutFeatures: ['big stacked title', 'blue offset title shadow', 'print grain'],
    problem: 'Duotone idea is right but registration/grain absent, so it looks flat-digital.',
    refinement: 'True 2-ink misregister: fluoro pink + blue offset by 3px, paper grain, big stacked display title.',
    notImplemented: [],
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    decision: 'keep',
    priority: 'anchor',
    composition: 'blueprint-grid',
    contentFixture: 'whitney',
    titleFont: 'Space Grotesk',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#0e3a63', ink: '#eaf2fb', sub: '#9cc3e6', line: '#6fa8d6', accent: '#eaf2fb', mapBg: '#0e3a63' },
    mapStyleRequirements: ['cyanotype blue', 'white index contours', 'draughting ticks'],
    routeStyleRequirements: ['yellow route', 'no endpoint markers'],
    requiredLayoutFeatures: ['map grid', 'titleblock corner', 'mono annotations'],
    problem: "Grid + cyan lines good; type is generic and there's no draughting language (ticks, callouts).",
    refinement: 'Add dimension ticks, a titleblock corner, mono annotations and white index contours on cyanotype blue.',
    notImplemented: [],
  },
  {
    id: 'moonstone',
    label: 'Moonstone',
    decision: 'merge',
    priority: 'normal',
    composition: 'blueprint-grid',
    contentFixture: 'dolomites',
    titleFont: 'Space Grotesk',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#dde3ea', ink: '#1f2a36', sub: '#5a6878', line: '#94a3b3', accent: '#2f6f9f', mapBg: '#dde3ea' },
    mapStyleRequirements: ['Blueprint light colorway', 'graphite lines on cool paper'],
    routeStyleRequirements: ['rust route', 'no endpoint markers'],
    requiredLayoutFeatures: ['same blueprint-grid layout as Blueprint'],
    problem: 'Same Space Grotesk + blueprint-grid; only a paler palette separates it.',
    refinement: "Demote to Blueprint 'Moonstone' light colorway (graphite lines on cool paper).",
    mergeTarget: 'blueprint',
    notImplemented: [],
  },
  {
    id: 'blueprint-strava',
    label: 'Trail Blueprint',
    decision: 'revise',
    priority: 'normal',
    composition: 'blueprint-strava',
    contentFixture: 'boston',
    titleFont: 'Space Grotesk',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#0c2e2a', ink: '#e9f6ef', sub: '#8fc7b3', line: '#5f9c8a', accent: '#3ddc97', mapBg: '#0c2e2a' },
    mapStyleRequirements: ['full-width technical map', 'drafting grid'],
    routeStyleRequirements: ['green route', 'no endpoint markers'],
    requiredLayoutFeatures: ['route stats bar below map', 'no splits table'],
    problem: "Near-clone of Blueprint, and the old splits table starved the map width - splits aren't a common RadMaps use case.",
    refinement: 'Drop splits. Full-width technical map on the drafting grid, with a clean route-stats bar below (distance, elevation, location, date).',
    notImplemented: [],
  },
  {
    id: 'electric-atlas',
    label: 'Electric Atlas',
    decision: 'revise',
    priority: 'normal',
    composition: 'blueprint-strava',
    contentFixture: 'boston',
    titleFont: 'Big Shoulders Display',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#0a0a12', ink: '#f4f4ff', sub: '#9a9ad0', line: '#3a3a66', accent: '#ff2e88', accent2: '#22e3ff', mapBg: '#0a0a12' },
    mapStyleRequirements: ['vivid night-athletic map', 'neon data ticks'],
    routeStyleRequirements: ['electric magenta route', 'controlled glow', 'no random leader labels'],
    requiredLayoutFeatures: ['technical stats bar', 'Big Shoulders title'],
    problem: "Shares blueprint-strava bones; needs to own the loud, high-energy end so it isn't 'blue blueprint'.",
    refinement: 'Push to vivid night-athletic: ink ground, electric magenta route with glow, Big Shoulders, neon data ticks.',
    notImplemented: [],
  },
  {
    id: 'field-journal',
    label: 'Field Journal',
    decision: 'keep',
    priority: 'normal',
    composition: 'journal-spread',
    contentFixture: 'scotland',
    titleFont: 'Cormorant Garamond',
    bodyFont: 'Source Serif 4',
    caseBehavior: 'title',
    palette: { paper: '#e8ded0', ink: '#2e2519', sub: '#6e5e44', line: '#b9a684', accent: '#6a4a2a', mapBg: '#efe7d8' },
    mapStyleRequirements: ['naturalist map', 'kraft tone'],
    routeStyleRequirements: ['brown route', 'clean halo'],
    requiredLayoutFeatures: ['two-column naturalist spread', 'tipped-in map plate', 'ruled margin notes', 'route specimen tag'],
    problem: 'Cormorant + journal idea is lovely but layout is a single block; no field-notes texture.',
    refinement: 'Two-column naturalist spread: tipped-in map plate, ruled margin notes, specimen tags, kraft tone.',
    notImplemented: [],
  },
  {
    id: 'botanical',
    label: 'Botanical Plate',
    decision: 'keep',
    priority: 'normal',
    composition: 'botanical-plate',
    contentFixture: 'dolomites',
    titleFont: 'Cormorant Garamond',
    bodyFont: 'Source Serif 4',
    caseBehavior: 'title',
    palette: { paper: '#eef0e6', ink: '#23311f', sub: '#5d6b4e', line: '#8a9a72', accent: '#3f5a32', mapBg: '#e7ecdc' },
    mapStyleRequirements: ['greener natural map', 'engraved plate identity'],
    routeStyleRequirements: ['green route', 'clean halo'],
    requiredLayoutFeatures: ['center framed plate', 'specimen caption'],
    problem: 'Reads too close to Field Journal (both Cormorant). Needs the engraved-plate identity.',
    refinement: 'Center a framed plate with ornamental corners + a serif specimen caption; greener natural map.',
    notImplemented: [],
  },
  {
    id: 'bold-modern',
    label: 'Modernist',
    decision: 'keep',
    priority: 'anchor',
    composition: 'modernist-block',
    contentFixture: 'rainier',
    titleFont: 'Big Shoulders Display',
    bodyFont: 'DM Sans',
    caseBehavior: 'upper',
    palette: { paper: '#f2f0ea', ink: '#16150f', sub: '#6a675d', line: '#16150f', accent: '#e2483d', mapBg: '#eae7df' },
    mapStyleRequirements: ['toner light base', 'asymmetric grid'],
    routeStyleRequirements: ['red route', 'endpoint markers'],
    requiredLayoutFeatures: ['oversized title bottom-left', 'color tab', 'map bleeds top-right'],
    problem: "Good Swiss bones but the title block floats; map and type aren't on one grid.",
    refinement: 'Lock to an asymmetric column grid: oversized title bottom-left, color tab, map bleeds top-right.',
    notImplemented: [],
  },
  {
    id: 'blackline',
    label: 'Blackline',
    decision: 'merge',
    priority: 'normal',
    composition: 'modernist-block',
    contentFixture: 'boston',
    titleFont: 'Big Shoulders Display',
    bodyFont: 'IBM Plex Sans',
    caseBehavior: 'upper',
    palette: { paper: '#f7f6f3', ink: '#0c0c0c', sub: '#6b6b6b', line: '#0c0c0c', accent: '#0c0c0c', mapBg: '#f2f1ee' },
    mapStyleRequirements: ['Modernist mono colorway'],
    routeStyleRequirements: ['pure black route', 'no registration proof marks'],
    requiredLayoutFeatures: ['same modernist-block layout as Modernist'],
    problem: 'Same Big Shoulders + modernist-block as Modernist; only ink-on-white differs.',
    refinement: "Fold into Modernist as the 'Blackline' mono colorway (no accent, pure black route).",
    mergeTarget: 'bold-modern',
    notImplemented: [],
  },
  {
    id: 'contour-wash',
    label: 'Contour Wash',
    decision: 'revise',
    priority: 'normal',
    composition: 'art-wash',
    contentFixture: 'dolomites',
    titleFont: 'Space Grotesk',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'upper',
    palette: { paper: '#eceae6', ink: '#2b2a28', sub: '#787570', line: '#c7c3bb', accent: '#7d8a86', mapBg: '#eceae6' },
    mapStyleRequirements: ['soft contour wash', 'full-bleed quiet art layout'],
    routeStyleRequirements: ['dark route', 'no endpoint markers'],
    requiredLayoutFeatures: ['small centered caption', 'lots of air'],
    problem: 'Sharing modernist-block with Modernist makes it read as a recolor, not an art print.',
    refinement: 'Give it its own quiet art layout: full-bleed soft contour wash, small centered caption, lots of air.',
    notImplemented: [],
  },
  {
    id: 'splits-stats',
    label: 'Trail Profile',
    decision: 'revise',
    priority: 'normal',
    composition: 'splits-grid',
    contentFixture: 'boston',
    titleFont: 'Space Grotesk',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#15181d', ink: '#f0f2f5', sub: '#9aa3ad', line: '#2c333c', accent: '#ff5a36', mapBg: '#15181d' },
    mapStyleRequirements: ['full-width map on top', 'dark technical contour base'],
    routeStyleRequirements: ['orange route', 'no endpoint markers'],
    requiredLayoutFeatures: ['elevation-profile chart below map', 'route stats', 'no per-mile split table'],
    problem: "Per-mile splits aren't a common RadMaps use case, and the bar grid competed with the map for the same grey.",
    refinement: 'Reframe around the route, not splits: full-width map on top, an elevation-profile chart below, then route stats (distance, elevation, location, date).',
    notImplemented: [],
  },
  {
    id: 'night-ride',
    label: 'Night Ride',
    decision: 'merge',
    priority: 'normal',
    composition: 'splits-grid',
    contentFixture: 'moab',
    titleFont: 'Oswald',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#0f1622', ink: '#eaf2fb', sub: '#8aa0b8', line: '#26303f', accent: '#28d6d6', mapBg: '#0f1622' },
    mapStyleRequirements: ['Trail Profile night colorway'],
    routeStyleRequirements: ['cyan route', 'no leader labels by default'],
    requiredLayoutFeatures: ['same Trail Profile layout'],
    problem: 'Same composition as Trail Profile; Oswald vs Space Grotesk is the only real difference.',
    refinement: "Merge as Trail Profile 'Night Ride' colorway (cyan route, deep navy) for cycling.",
    mergeTarget: 'splits-stats',
    notImplemented: [],
  },
  {
    id: 'marathon-bib',
    label: 'Marathon',
    decision: 'keep',
    priority: 'normal',
    composition: 'bib-numerals',
    contentFixture: 'boston',
    titleFont: 'Bebas Neue',
    bodyFont: 'Atkinson Hyperlegible Next',
    caseBehavior: 'upper',
    palette: { paper: '#f4f1ea', ink: '#14264a', sub: '#5a6477', line: '#c4ccd8', accent: '#e0322c', mapBg: '#eeeae0' },
    mapStyleRequirements: ['race-day collar', 'bib numeral backdrop'],
    routeStyleRequirements: ['red route', 'endpoint markers'],
    requiredLayoutFeatures: ['giant ghosted bib numeral', 'finish data headline'],
    problem: 'Bib idea is great but the numeral is timid and the finish data is buried.',
    refinement: 'Giant ghosted bib numeral behind the map, finish time as the headline, race-day collar at the foot.',
    notImplemented: [],
  },
  {
    id: 'dark-sky',
    label: 'Dark Sky',
    decision: 'keep',
    priority: 'anchor',
    composition: 'darksky-stars',
    contentFixture: 'whitney',
    titleFont: 'Cormorant Garamond',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'title',
    palette: { paper: '#0a1024', ink: '#eef1fb', sub: '#9aa6cc', line: '#22305a', accent: '#e8c66a', mapBg: '#0a1024' },
    mapStyleRequirements: ['star field up top', 'ridge-line horizon', 'dark relief map'],
    routeStyleRequirements: ['gold route glints below', 'no leader labels by default'],
    requiredLayoutFeatures: ['Cormorant title in sky', 'terrain and sky read as one scene'],
    problem: 'Beautiful concept; needs a real horizon so sky and terrain read as one scene.',
    refinement: 'Star field up top, ridge-line silhouette at a clean horizon, route glints below; Cormorant title in the sky.',
    notImplemented: [],
  },
  {
    id: 'copper-night',
    label: 'Copper Night',
    decision: 'merge',
    priority: 'normal',
    composition: 'darksky-stars',
    contentFixture: 'dolomites',
    titleFont: 'Cormorant Garamond',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'title',
    palette: { paper: '#160e0a', ink: '#f6ece0', sub: '#c8a585', line: '#3a261a', accent: '#d98a3f', mapBg: '#160e0a' },
    mapStyleRequirements: ['Dark Sky copper colorway'],
    routeStyleRequirements: ['warm bronze route', 'no leader labels by default'],
    requiredLayoutFeatures: ['same darksky-stars layout as Dark Sky'],
    problem: 'Same darksky-stars + Cormorant; a copper recolor of Dark Sky.',
    refinement: "Merge as Dark Sky 'Copper' colorway (warm bronze stars + route).",
    mergeTarget: 'dark-sky',
    notImplemented: [],
  },
  {
    id: 'brutalist',
    label: 'Brutalist',
    decision: 'keep',
    priority: 'normal',
    composition: 'brutalist-slab',
    contentFixture: 'boston',
    titleFont: 'Bebas Neue',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#e7e4dc', ink: '#111111', sub: '#5a5a55', line: '#111111', accent: '#ff3b00', mapBg: '#ddd9cf' },
    mapStyleRequirements: ['concrete palette', 'raw but deliberate', 'exposed baseline grid'],
    routeStyleRequirements: ['orange route', 'no random elevation chart', 'no route-attached proof dashes'],
    requiredLayoutFeatures: ['hairline registration marks', 'monumental Bebas word cropped at edge', 'cropped edge tension'],
    problem: 'Wants to be raw but currently just looks under-designed; no grid tension or scale jump.',
    refinement: 'Exposed baseline grid, hairline registration marks, one monumental Bebas word cropped at the edge.',
    notImplemented: [],
  },
  {
    id: 'cartouche-place',
    label: 'Cartouche',
    decision: 'new',
    priority: 'normal',
    composition: 'place-frame',
    contentFixture: 'cdmx',
    titleFont: 'Playfair Display',
    bodyFont: 'Source Serif 4',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#f4efe4', ink: '#20242b', sub: '#6b6f78', line: '#c9c2b2', accent: '#9a3b27', mapBg: '#f0eadc' },
    mapStyleRequirements: ['engraved street-network plate', 'optional pin instead of route'],
    routeStyleRequirements: ['route optional', 'no fake route art for place-only maps'],
    requiredLayoutFeatures: ['decorative cartouche title', 'coordinate footer', 'elevation footer'],
    problem: 'Place orders currently get forced into a route layout with an empty trail.',
    refinement: 'Engraved street-network plate with a decorative cartouche title, coordinate + elevation footer, optional pin instead of a route.',
    notImplemented: [],
  },
  {
    id: 'sea-chart',
    label: 'Sea Chart',
    decision: 'new',
    priority: 'normal',
    composition: 'sea-chart',
    contentFixture: 'scotland',
    titleFont: 'Libre Baskerville',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'title',
    palette: { paper: '#ede6d2', ink: '#1d2a36', sub: '#5a6b74', line: '#aebfae', accent: '#b23a6a', mapBg: '#e6f0ec' },
    mapStyleRequirements: ['nautical chart paper', 'depth sounding language only when clean', 'warm chart typography'],
    routeStyleRequirements: ['magenta course line', 'no fake static chart art'],
    requiredLayoutFeatures: ['chart title treatment', 'mono data where present', 'vector compass rose', 'dashed rhumb lines', 'depth soundings'],
    problem: 'Water-adjacent routes look out of place on terrain-only contour themes.',
    refinement: 'Depth-sounding dots, compass rose, dashed rhumb lines on warm chart paper; route as a magenta course line.',
    notImplemented: [],
  },
  {
    id: 'relief-shaded',
    label: 'Shaded Relief',
    decision: 'new',
    priority: 'normal',
    composition: 'editorial-tall',
    contentFixture: 'rainier',
    titleFont: 'Newsreader',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'title',
    palette: { paper: '#efe9dd', ink: '#2a2620', sub: '#6f685b', line: '#cabfa8', accent: '#b4502a', mapBg: '#e9e0cd' },
    mapStyleRequirements: ['premium National Geographic shaded-terrain feel', 'hypsometric tinted bands', 'fine contours'],
    routeStyleRequirements: ['confident ink route', 'clean halo'],
    requiredLayoutFeatures: ['quiet serif caption', 'big landscape print feel'],
    problem: 'Outdoors buyers want dimensional terrain, not just line contours.',
    refinement: 'Hypsometric tinted bands under fine contours for a relief feel; quiet serif caption; route as a confident ink line.',
    notImplemented: [],
  },
  {
    id: 'transit-diagram',
    label: 'Transit',
    decision: 'new',
    priority: 'normal',
    composition: 'transit-diagram',
    contentFixture: 'napa',
    titleFont: 'Outfit',
    bodyFont: 'IBM Plex Sans',
    monoFont: 'IBM Plex Mono',
    caseBehavior: 'upper',
    palette: { paper: '#f7f5f0', ink: '#181818', sub: '#6a6a6a', line: '#dad7cf', accent: '#7a1fa2', accent2: '#1f8a5b', mapBg: '#f7f5f0' },
    mapStyleRequirements: ['Beck-style 45/90 route abstraction from uploaded GPX/stops', 'not random chrome'],
    routeStyleRequirements: ['purple abstract route', 'ringed station nodes', 'stop labels'],
    requiredLayoutFeatures: ['bold mono legend', 'tour sequence language', 'route-derived 45/90 line', 'ringed station key'],
    problem: "Tour/stops itineraries don't suit a literal trace; users want a stylised line with labelled stations.",
    refinement: 'Beck-style 45/90 route, ringed station nodes with stop labels, bold mono legend; works for any stop list.',
    notImplemented: [],
  },
  {
    id: 'plein-air',
    label: 'Plein Air',
    decision: 'new',
    priority: 'normal',
    composition: 'art-wash',
    contentFixture: 'dolomites',
    titleFont: 'Cormorant Garamond',
    bodyFont: 'Source Sans 3',
    caseBehavior: 'title',
    palette: { paper: '#f6f1e8', ink: '#33302a', sub: '#7a7568', line: '#d8cfbd', accent: '#c2683f', mapBg: '#f3ede1' },
    mapStyleRequirements: ['loose watercolor washes', 'light contour', 'deckle-edge frame'],
    routeStyleRequirements: ['brushed route line', 'no excessive pigment bleed'],
    requiredLayoutFeatures: ['soft hand-painted option', 'italic hand-set feeling', 'deckle-edge frame', 'watercolor palette marks'],
    problem: 'No soft, hand-painted option for sentimental trip prints.',
    refinement: 'Loose watercolour washes under a light contour, hand-set italic title, deckle-edge frame, route as a brushed line.',
    notImplemented: [],
  },
]

export const THEME_SPEC_IDS = THEME_SPEC_CONTRACTS.map(theme => theme.id)

export function getThemeSpecContract(id: ColorTheme | string): ThemeSpecContract | undefined {
  return THEME_SPEC_CONTRACTS.find(theme => theme.id === id)
}
