/**
 * Shared poster typography and layout data.
 * Single source of truth for MapPreview.vue in editor and AWS render pages.
 *
 * Sizes are stored as plain numbers — consumers append the appropriate CSS unit:
 *   MapPreview.vue: `${profile.titleSize}cqh`
 */

import type { StyleConfig } from '~/types'
import { getPosterCompositionProfile } from '~/utils/posterCompositions'

// ── Interfaces ────────────────────────────────────────────────────────────────

export interface PosterTypographyProfile {
  titleFont: string       // full font stack, e.g. "'Work Sans', sans-serif"
  titleWeight: string
  titleTracking: string
  titleCase: string       // 'uppercase' | 'none'
  titleSize: number       // unit-less (append 'cqh' or 'vh')
  titleLineHeight: string
  subFont: string
  subWeight: string
  subTracking: string
  subSize: number         // unit-less
  statsFont: string
  statsWeight: string
}

export interface PosterLayoutProfile {
  titleAlign: 'center' | 'left'
  titlePosition: 'top' | 'bottom'
}

// ── Font helpers ──────────────────────────────────────────────────────────────

export const SERIF_FONTS = new Set([
  'Source Serif 4',
  'Newsreader',
  'Playfair Display',
  'Cormorant Garamond',
  'Libre Baskerville',
  'DM Serif Display',
])

export function toFontStack(family: string): string {
  return `'${family}', ${SERIF_FONTS.has(family) ? 'serif' : 'sans-serif'}`
}

// ── Typography table ──────────────────────────────────────────────────────────

const THEME_TYPOGRAPHY: Record<string, PosterTypographyProfile> = {
  // ── Family A ──────────────────────────────────────────────────────────────
  chalk: {
    titleFont: "'Work Sans', sans-serif",
    titleWeight: '300',
    titleTracking: '0.38em',
    titleCase: 'uppercase',
    titleSize: 3.4,
    titleLineHeight: '1.15',
    subFont: "'Work Sans', sans-serif",
    subWeight: '400',
    subTracking: '0.28em',
    subSize: 1.0,
    statsFont: "'Work Sans', sans-serif",
    statsWeight: '500',
  },
  topaz: {
    titleFont: "'Space Grotesk', sans-serif",
    titleWeight: '700',
    titleTracking: '0.06em',
    titleCase: 'uppercase',
    titleSize: 4.4,
    titleLineHeight: '1.05',
    subFont: "'Space Grotesk', sans-serif",
    subWeight: '400',
    subTracking: '0.22em',
    subSize: 1.05,
    statsFont: "'Space Grotesk', sans-serif",
    statsWeight: '600',
  },
  dusk: {
    titleFont: "'DM Serif Display', serif",
    titleWeight: '400',
    titleTracking: '0.03em',
    titleCase: 'none',
    titleSize: 4.8,
    titleLineHeight: '1.1',
    subFont: "'DM Sans', sans-serif",
    subWeight: '400',
    subTracking: '0.22em',
    subSize: 1.0,
    statsFont: "'DM Sans', sans-serif",
    statsWeight: '500',
  },
  obsidian: {
    titleFont: "'Big Shoulders Display', sans-serif",
    titleWeight: '800',
    titleTracking: '0',
    titleCase: 'uppercase',
    titleSize: 5.8,
    titleLineHeight: '0.95',
    subFont: "'DM Sans', sans-serif",
    subWeight: '400',
    subTracking: '0.35em',
    subSize: 1.0,
    statsFont: "'Big Shoulders Display', sans-serif",
    statsWeight: '700',
  },
  forest: {
    titleFont: "'Oswald', sans-serif",
    titleWeight: '600',
    titleTracking: '0.08em',
    titleCase: 'uppercase',
    titleSize: 4.6,
    titleLineHeight: '1.05',
    subFont: "'Oswald', sans-serif",
    subWeight: '300',
    subTracking: '0.22em',
    subSize: 1.0,
    statsFont: "'Oswald', sans-serif",
    statsWeight: '500',
  },
  midnight: {
    titleFont: "'Fjalla One', sans-serif",
    titleWeight: '400',
    titleTracking: '0.12em',
    titleCase: 'uppercase',
    titleSize: 4.8,
    titleLineHeight: '1.05',
    subFont: "'DM Sans', sans-serif",
    subWeight: '300',
    subTracking: '0.32em',
    subSize: 1.0,
    statsFont: "'Fjalla One', sans-serif",
    statsWeight: '400',
  },
  // ── Family B ──────────────────────────────────────────────────────────────
  editorial: {
    titleFont: "'Playfair Display', serif",
    titleWeight: '400',
    titleTracking: '0.02em',
    titleCase: 'none',
    titleSize: 5.0,
    titleLineHeight: '1.1',
    subFont: "'Playfair Display', serif",
    subWeight: '400',
    subTracking: '0.18em',
    subSize: 1.0,
    statsFont: "'Libre Baskerville', serif",
    statsWeight: '400',
  },
  bauhaus: {
    titleFont: "'Big Shoulders Display', sans-serif",
    titleWeight: '900',
    titleTracking: '0',
    titleCase: 'uppercase',
    titleSize: 6.8,
    titleLineHeight: '0.9',
    subFont: "'DM Sans', sans-serif",
    subWeight: '400',
    subTracking: '0.28em',
    subSize: 0.95,
    statsFont: "'Big Shoulders Display', sans-serif",
    statsWeight: '700',
  },
  vintage: {
    titleFont: "'DM Serif Display', serif",
    titleWeight: '400',
    titleTracking: '0.04em',
    titleCase: 'none',
    titleSize: 5.2,
    titleLineHeight: '1.08',
    subFont: "'DM Serif Display', serif",
    subWeight: '400',
    subTracking: '0.22em',
    subSize: 1.0,
    statsFont: "'DM Sans', sans-serif",
    statsWeight: '400',
  },
  brutalist: {
    titleFont: "'Bebas Neue', sans-serif",
    titleWeight: '400',
    titleTracking: '0.07em',
    titleCase: 'uppercase',
    titleSize: 7.2,
    titleLineHeight: '0.92',
    subFont: "'DM Sans', sans-serif",
    subWeight: '700',
    subTracking: '0.35em',
    subSize: 0.9,
    statsFont: "'Bebas Neue', sans-serif",
    statsWeight: '400',
  },
  risograph: {
    titleFont: "'Oswald', sans-serif",
    titleWeight: '500',
    titleTracking: '0.10em',
    titleCase: 'uppercase',
    titleSize: 5.0,
    titleLineHeight: '1.0',
    subFont: "'Oswald', sans-serif",
    subWeight: '300',
    subTracking: '0.25em',
    subSize: 1.0,
    statsFont: "'Work Sans', sans-serif",
    statsWeight: '500',
  },
  blueprint: {
    titleFont: "'Space Grotesk', sans-serif",
    titleWeight: '700',
    titleTracking: '0.14em',
    titleCase: 'uppercase',
    titleSize: 4.2,
    titleLineHeight: '1.05',
    subFont: "'Space Grotesk', sans-serif",
    subWeight: '400',
    subTracking: '0.28em',
    subSize: 0.9,
    statsFont: "'Space Grotesk', sans-serif",
    statsWeight: '600',
  },
  kertok: {
    titleFont: "'Work Sans', sans-serif",
    titleWeight: '200',
    titleTracking: '0.06em',
    titleCase: 'none',
    titleSize: 4.6,
    titleLineHeight: '1.12',
    subFont: "'Work Sans', sans-serif",
    subWeight: '300',
    subTracking: '0.20em',
    subSize: 0.95,
    statsFont: "'Work Sans', sans-serif",
    statsWeight: '300',
  },
  'mid-century': {
    titleFont: "'Oswald', sans-serif",
    titleWeight: '400',
    titleTracking: '0.16em',
    titleCase: 'uppercase',
    titleSize: 4.4,
    titleLineHeight: '1.05',
    subFont: "'Work Sans', sans-serif",
    subWeight: '400',
    subTracking: '0.30em',
    subSize: 0.95,
    statsFont: "'Oswald', sans-serif",
    statsWeight: '400',
  },
  'topo-art': {
    titleFont: "'Work Sans', sans-serif",
    titleWeight: '400',
    titleTracking: '0.28em',
    titleCase: 'uppercase',
    titleSize: 3.6,
    titleLineHeight: '1.15',
    subFont: "'Work Sans', sans-serif",
    subWeight: '300',
    subTracking: '0.22em',
    subSize: 0.95,
    statsFont: "'Work Sans', sans-serif",
    statsWeight: '400',
  },
  'dark-sky': {
    titleFont: "'Fjalla One', sans-serif",
    titleWeight: '400',
    titleTracking: '0.08em',
    titleCase: 'uppercase',
    titleSize: 5.4,
    titleLineHeight: '1.0',
    subFont: "'DM Sans', sans-serif",
    subWeight: '300',
    subTracking: '0.35em',
    subSize: 1.0,
    statsFont: "'Fjalla One', sans-serif",
    statsWeight: '400',
  },
}

// ── Layout table ──────────────────────────────────────────────────────────────

const THEME_LAYOUT: Record<string, PosterLayoutProfile> = {
  // Family A — classic centered top
  chalk:         { titleAlign: 'center', titlePosition: 'top' },
  topaz:         { titleAlign: 'center', titlePosition: 'top' },
  dusk:          { titleAlign: 'center', titlePosition: 'top' },
  obsidian:      { titleAlign: 'center', titlePosition: 'top' },
  forest:        { titleAlign: 'center', titlePosition: 'top' },
  midnight:      { titleAlign: 'center', titlePosition: 'top' },
  // Family B — varied layouts
  editorial:     { titleAlign: 'left',   titlePosition: 'top' },
  bauhaus:       { titleAlign: 'left',   titlePosition: 'bottom' },
  vintage:       { titleAlign: 'center', titlePosition: 'top' },
  brutalist:     { titleAlign: 'left',   titlePosition: 'bottom' },
  risograph:     { titleAlign: 'left',   titlePosition: 'top' },
  blueprint:     { titleAlign: 'left',   titlePosition: 'bottom' },
  kertok:        { titleAlign: 'left',   titlePosition: 'top' },
  'mid-century': { titleAlign: 'center', titlePosition: 'bottom' },
  'topo-art':    { titleAlign: 'center', titlePosition: 'top' },
  'dark-sky':    { titleAlign: 'center', titlePosition: 'bottom' },
}

Object.assign(THEME_TYPOGRAPHY, {
  'editorial-minimal': {
    ...THEME_TYPOGRAPHY.editorial,
    titleFont: "'Playfair Display', serif",
    titleWeight: '500',
    titleTracking: '0',
    titleCase: 'none',
    titleSize: 4.62,
    titleLineHeight: '1',
    subFont: "'Source Serif 4', serif",
    subWeight: '400',
    subTracking: '0.08em',
    statsFont: "'Source Serif 4', serif",
    statsWeight: '420',
  },
  'usgs-vintage': {
    ...THEME_TYPOGRAPHY.vintage,
    titleFont: "'Libre Baskerville', serif",
    titleWeight: '600',
    titleTracking: '0.01em',
    titleCase: 'none',
    titleSize: 4.12,
    titleLineHeight: '1.03',
    subFont: "'Source Sans 3', sans-serif",
    subWeight: '600',
    subTracking: '0.14em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '640',
  },
  'midcentury-travel': {
    ...THEME_TYPOGRAPHY['mid-century'],
    titleFont: "'Oswald', sans-serif",
    titleWeight: '600',
    titleTracking: '0.06em',
    titleSize: 4.74,
    titleLineHeight: '0.98',
    subFont: "'Source Sans 3', sans-serif",
    subTracking: '0.14em',
    statsWeight: '760',
  },
  risograph: {
    ...THEME_TYPOGRAPHY.risograph,
    titleFont: "'Big Shoulders Display', sans-serif",
    titleWeight: '800',
    titleTracking: '0',
    titleSize: 8.1,
    titleLineHeight: '0.8',
    subFont: "'Work Sans', sans-serif",
    subTracking: '0.16em',
    statsFont: "'Work Sans', sans-serif",
    statsWeight: '650',
  },
  blueprint: {
    ...THEME_TYPOGRAPHY.blueprint,
    titleFont: "'Space Grotesk', sans-serif",
    titleTracking: '0.07em',
    titleSize: 3.68,
    subFont: "'IBM Plex Sans', sans-serif",
    subTracking: '0.16em',
    statsFont: "'IBM Plex Sans', sans-serif",
  },
  'blueprint-strava': {
    ...THEME_TYPOGRAPHY.blueprint,
    titleFont: "'Space Grotesk', sans-serif",
    titleTracking: '0.05em',
    titleSize: 3.34,
    subFont: "'IBM Plex Sans', sans-serif",
    subTracking: '0.16em',
    statsFont: "'IBM Plex Sans', sans-serif",
  },
  'field-journal': {
    ...THEME_TYPOGRAPHY.kertok,
    titleFont: "'Cormorant Garamond', serif",
    titleWeight: '500',
    titleTracking: '0.01em',
    titleCase: 'none',
    titleSize: 4.7,
    titleLineHeight: '0.98',
    subFont: "'Source Serif 4', serif",
    subTracking: '0.06em',
    statsFont: "'Source Serif 4', serif",
    statsWeight: '520',
  },
  'bold-modern': {
    ...THEME_TYPOGRAPHY.bauhaus,
    titleFont: "'Big Shoulders Display', sans-serif",
    titleWeight: '900',
    titleTracking: '0.015em',
    titleSize: 9.72,
    titleLineHeight: '0.88',
    subFont: "'DM Sans', sans-serif",
    subTracking: '0.18em',
    statsFont: "'DM Sans', sans-serif",
    statsWeight: '820',
  },
  'contour-wash': {
    ...THEME_TYPOGRAPHY.editorial,
    titleFont: "'Space Grotesk', sans-serif",
    titleWeight: '500',
    titleTracking: '0.015em',
    titleSize: 5.05,
    titleLineHeight: '1.06',
    titleCase: 'uppercase',
    subFont: "'Source Sans 3', sans-serif",
    subWeight: '500',
    subTracking: '0.16em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '600',
  },
  'splits-stats': {
    ...THEME_TYPOGRAPHY.blueprint,
    titleFont: "'Space Grotesk', sans-serif",
    titleTracking: '0.04em',
    titleSize: 3.62,
    subFont: "'IBM Plex Sans', sans-serif",
    subTracking: '0.16em',
    statsFont: "'IBM Plex Sans', sans-serif",
    statsWeight: '850',
  },
  'marathon-bib': {
    ...THEME_TYPOGRAPHY.brutalist,
    titleFont: "'Bebas Neue', sans-serif",
    titleTracking: '0.04em',
    titleSize: 5.82,
    titleLineHeight: '0.9',
    subFont: "'Atkinson Hyperlegible Next', sans-serif",
    statsFont: "'Atkinson Hyperlegible Next', sans-serif",
    statsWeight: '900',
  },
  'dark-sky': {
    ...THEME_TYPOGRAPHY['dark-sky'],
    titleFont: "'Cormorant Garamond', serif",
    titleWeight: '500',
    titleTracking: '0.02em',
    titleCase: 'none',
    titleSize: 4.56,
    titleLineHeight: '0.98',
    subFont: "'Source Sans 3', sans-serif",
    subTracking: '0.16em',
    statsFont: "'Source Sans 3', sans-serif",
  },
  botanical: {
    ...THEME_TYPOGRAPHY.kertok,
    titleFont: "'Cormorant Garamond', serif",
    titleWeight: '500',
    titleTracking: '0.01em',
    titleCase: 'none',
    titleSize: 4.48,
    titleLineHeight: '1',
    subFont: "'Source Serif 4', serif",
    subTracking: '0.06em',
    statsFont: "'Source Serif 4', serif",
    statsWeight: '520',
  },
  brutalist: {
    ...THEME_TYPOGRAPHY.brutalist,
    titleFont: "'Bebas Neue', sans-serif",
    titleTracking: '0.045em',
    titleSize: 6.2,
    titleLineHeight: '0.88',
    subFont: "'IBM Plex Sans', sans-serif",
    subTracking: '0.14em',
    statsFont: "'IBM Plex Sans', sans-serif",
    statsWeight: '700',
  },
  'classic-trail': {
    ...THEME_TYPOGRAPHY.vintage,
    titleFont: "'Libre Baskerville', serif",
    titleWeight: '600',
    titleTracking: '0.01em',
    titleCase: 'none',
    titleSize: 4.18,
    titleLineHeight: '1.02',
    subFont: "'Source Sans 3', sans-serif",
    subTracking: '0.12em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '620',
  },
  'ranch-ochre': {
    ...THEME_TYPOGRAPHY['mid-century'],
    titleFont: "'Oswald', sans-serif",
    titleWeight: '600',
    titleTracking: '0.07em',
    titleSize: 4.62,
    titleLineHeight: '0.98',
    subFont: "'Source Sans 3', sans-serif",
    subWeight: '600',
    subTracking: '0.14em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '600',
  },
  blackline: {
    ...THEME_TYPOGRAPHY.bauhaus,
    titleFont: "'Big Shoulders Display', sans-serif",
    titleWeight: '900',
    titleTracking: '0.01em',
    titleSize: 6.05,
    titleLineHeight: '0.9',
    subFont: "'IBM Plex Sans', sans-serif",
    subWeight: '700',
    subTracking: '0.12em',
    statsFont: "'IBM Plex Sans', sans-serif",
    statsWeight: '700',
  },
  'copper-night': {
    ...THEME_TYPOGRAPHY['dark-sky'],
    titleFont: "'Cormorant Garamond', serif",
    titleWeight: '500',
    titleTracking: '0.02em',
    titleCase: 'none',
    titleSize: 4.46,
    titleLineHeight: '0.98',
    subFont: "'Source Sans 3', sans-serif",
    subWeight: '500',
    subTracking: '0.16em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '600',
  },
  moonstone: {
    ...THEME_TYPOGRAPHY.blueprint,
    titleFont: "'Space Grotesk', sans-serif",
    titleWeight: '700',
    titleTracking: '0.04em',
    titleSize: 3.55,
    titleLineHeight: '1.02',
    subFont: "'IBM Plex Sans', sans-serif",
    subTracking: '0.12em',
    statsFont: "'IBM Plex Sans', sans-serif",
    statsWeight: '600',
  },
  'night-ride': {
    ...THEME_TYPOGRAPHY.blueprint,
    titleFont: "'Oswald', sans-serif",
    titleWeight: '700',
    titleTracking: '0.06em',
    titleSize: 4.05,
    titleLineHeight: '0.96',
    subFont: "'IBM Plex Sans', sans-serif",
    subWeight: '600',
    subTracking: '0.14em',
    statsFont: "'IBM Plex Sans', sans-serif",
    statsWeight: '800',
  },
  'daybreak-trace': {
    ...THEME_TYPOGRAPHY['mid-century'],
    titleFont: "'Oswald', sans-serif",
    titleWeight: '600',
    titleTracking: '0.07em',
    titleCase: 'uppercase',
    titleSize: 4.62,
    titleLineHeight: '0.98',
    subFont: "'Source Sans 3', sans-serif",
    subWeight: '600',
    subTracking: '0.12em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '700',
  },
  'electric-atlas': {
    ...THEME_TYPOGRAPHY.blueprint,
    titleFont: "'Big Shoulders Display', sans-serif",
    titleWeight: '900',
    titleTracking: '0.03em',
    titleSize: 4.7,
    titleLineHeight: '0.92',
    subFont: "'IBM Plex Sans', sans-serif",
    subWeight: '600',
    subTracking: '0.14em',
    statsFont: "'IBM Plex Sans', sans-serif",
    statsWeight: '800',
  },
  'cartouche-place': {
    ...THEME_TYPOGRAPHY.editorial,
    titleFont: "'Playfair Display', serif",
    titleWeight: '600',
    titleTracking: '0.01em',
    titleCase: 'none',
    titleSize: 6.45,
    titleLineHeight: '0.94',
    subFont: "'Source Serif 4', serif",
    subWeight: '400',
    subTracking: '0.08em',
    statsFont: "'IBM Plex Mono', monospace",
    statsWeight: '500',
  },
  'sea-chart': {
    ...THEME_TYPOGRAPHY.vintage,
    titleFont: "'Libre Baskerville', serif",
    titleWeight: '700',
    titleTracking: '0',
    titleCase: 'none',
    titleSize: 4.15,
    titleLineHeight: '0.96',
    subFont: "'IBM Plex Sans', sans-serif",
    subWeight: '500',
    subTracking: '0.18em',
    statsFont: "'IBM Plex Mono', monospace",
    statsWeight: '500',
  },
  'relief-shaded': {
    ...THEME_TYPOGRAPHY.editorial,
    titleFont: "'Newsreader', serif",
    titleWeight: '500',
    titleTracking: '0.01em',
    titleCase: 'none',
    titleSize: 4.35,
    titleLineHeight: '1.04',
    subFont: "'Source Sans 3', sans-serif",
    subWeight: '500',
    subTracking: '0.14em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '650',
  },
  'transit-diagram': {
    ...THEME_TYPOGRAPHY.blueprint,
    titleFont: "'Outfit', sans-serif",
    titleWeight: '800',
    titleTracking: '0',
    titleCase: 'uppercase',
    titleSize: 6.9,
    titleLineHeight: '0.9',
    subFont: "'IBM Plex Sans', sans-serif",
    subWeight: '600',
    subTracking: '0.16em',
    statsFont: "'IBM Plex Mono', monospace",
    statsWeight: '700',
  },
  'plein-air': {
    ...THEME_TYPOGRAPHY['dark-sky'],
    titleFont: "'Cormorant Garamond', serif",
    titleWeight: '500',
    titleTracking: '0.01em',
    titleCase: 'none',
    titleSize: 4.38,
    titleLineHeight: '1.02',
    subFont: "'Source Sans 3', sans-serif",
    subWeight: '400',
    subTracking: '0.14em',
    statsFont: "'Source Sans 3', sans-serif",
    statsWeight: '550',
  },
})

// ── Public API ────────────────────────────────────────────────────────────────

export function getPosterTypography(
  styleConfig: Pick<StyleConfig, 'color_theme'> & Partial<Pick<StyleConfig, 'font_family' | 'body_font_family'>>,
): PosterTypographyProfile {
  const base = THEME_TYPOGRAPHY[styleConfig.color_theme ?? 'chalk'] ?? THEME_TYPOGRAPHY.chalk
  const titleOverride = styleConfig.font_family
  if (titleOverride) {
    const bodyOverride = styleConfig.body_font_family ?? titleOverride
    return {
      ...base,
      titleFont: toFontStack(titleOverride as string),
      subFont: toFontStack(bodyOverride as string),
      statsFont: toFontStack(bodyOverride as string),
    }
  }
  return base
}

export function getPosterLayout(
  styleConfig: Pick<StyleConfig, 'color_theme' | 'composition'>,
): PosterLayoutProfile {
  const composition = getPosterCompositionProfile(styleConfig)
  if (composition.id !== 'legacy-classic') {
    return {
      titleAlign: composition.titleAlign,
      titlePosition: composition.titlePosition,
    }
  }
  return THEME_LAYOUT[styleConfig.color_theme ?? 'chalk'] ?? THEME_LAYOUT.chalk
}
